; STAGE ENDING: final cinematic + escape on the pteranodon-creature.
;
; Gameplay role: closing cinematic after all gameplay stages
; complete. The alien friend rescues Lester one last time and they
; ride off together on a giant flying creature.
;
; This file: dos_1992 (Daniel Morais MS-DOS port)
;
;
; Structure: only 28 folded bodies. Mostly DRAW_CIN_<N>_TO_<M>
; sequences and PALETTE_FADE animations. Like CAVES, has empty
; post-fold chunks blocking the cleanup pass.
;
; Generated by AnotherWorld_VMTools
;@include "../_common_vars.inc"
CINEMATIC_000		EQU 0x121C
CINEMATIC_001		EQU 0x0DDC
CINEMATIC_002		EQU 0x1078
CINEMATIC_003		EQU 0x0D64
CINEMATIC_004		EQU 0x2ED0
CINEMATIC_005		EQU 0x25B0
CINEMATIC_006		EQU 0x2824
CINEMATIC_007		EQU 0x337C
CINEMATIC_008		EQU 0x1238
CINEMATIC_009		EQU 0x1318
CINEMATIC_010		EQU 0x4498
CINEMATIC_011		EQU 0x179A
CINEMATIC_012		EQU 0x1730
CINEMATIC_013		EQU 0x1480
CINEMATIC_014		EQU 0x15E8
CINEMATIC_015		EQU 0x1594
CINEMATIC_016		EQU 0x1498
CINEMATIC_017		EQU 0x14EC
CINEMATIC_018		EQU 0x1540
CINEMATIC_019		EQU 0x1800
CINEMATIC_020		EQU 0x1854
CINEMATIC_021		EQU 0x1968
CINEMATIC_022		EQU 0x18A8
CINEMATIC_023		EQU 0x190A
CINEMATIC_024		EQU 0x16C4
CINEMATIC_025		EQU 0x163C
CINEMATIC_026		EQU 0x1A88
CINEMATIC_027		EQU 0x1B48
CINEMATIC_028		EQU 0x1C10
CINEMATIC_029		EQU 0x1CC8
CINEMATIC_030		EQU 0x1D80
CINEMATIC_031		EQU 0x1E38
CINEMATIC_032		EQU 0x1F4C
CINEMATIC_033		EQU 0x2004
CINEMATIC_034		EQU 0x20CC
CINEMATIC_035		EQU 0x2194
CINEMATIC_036		EQU 0x2258
CINEMATIC_037		EQU 0x23C0
CINEMATIC_038		EQU 0x2758
CINEMATIC_039		EQU 0x290A
CINEMATIC_040		EQU 0x267E
CINEMATIC_041		EQU 0x29C8
CINEMATIC_042		EQU 0x29E4
CINEMATIC_043		EQU 0x2A24
CINEMATIC_044		EQU 0x2A64
CINEMATIC_045		EQU 0x2AB4
CINEMATIC_046		EQU 0x2B1C
CINEMATIC_047		EQU 0x2B88
CINEMATIC_048		EQU 0x2BC8
CINEMATIC_049		EQU 0x2C08
CINEMATIC_050		EQU 0x2C58
CINEMATIC_051		EQU 0x2CC0
CINEMATIC_052		EQU 0x3F60
CINEMATIC_053		EQU 0x3F04
CINEMATIC_054		EQU 0x3E4C
CINEMATIC_055		EQU 0x3D8C
CINEMATIC_056		EQU 0x3DEC
CINEMATIC_057		EQU 0x3EA8
CINEMATIC_058		EQU 0x4AE0
CINEMATIC_059		EQU 0x4D76
CINEMATIC_060		EQU 0x4D92
CINEMATIC_061		EQU 0x4DAE
CINEMATIC_062		EQU 0x4DCA
CINEMATIC_063		EQU 0x4DE6
CINEMATIC_064		EQU 0x4E02
CINEMATIC_065		EQU 0x4E1E
CINEMATIC_066		EQU 0x35F8
CINEMATIC_067		EQU 0x49DC
CINEMATIC_068		EQU 0x47D4
CINEMATIC_069		EQU 0x48D8
CINEMATIC_070		EQU 0x4D6A
CINEMATIC_071		EQU 0x46E8
CINEMATIC_072		EQU 0x46A8
CINEMATIC_073		EQU 0x4668
CINEMATIC_074		EQU 0x4654
CINEMATIC_075		EQU 0x3ACC
CINEMATIC_076		EQU 0x3B18
CINEMATIC_077		EQU 0x3B64
CINEMATIC_078		EQU 0x3BAC
CINEMATIC_079		EQU 0x3C00
CINEMATIC_080		EQU 0x3C58
CINEMATIC_081		EQU 0x3CA0
CINEMATIC_082		EQU 0x3CEC
CINEMATIC_083		EQU 0x3D38
CINEMATIC_084		EQU 0x3A7C
CINEMATIC_085		EQU 0x3A2C
CINEMATIC_086		EQU 0x36D4
CINEMATIC_087		EQU 0x38B0
CINEMATIC_088		EQU 0x3814
CINEMATIC_089		EQU 0x385C
CINEMATIC_090		EQU 0x3720
CINEMATIC_091		EQU 0x38FC
CINEMATIC_092		EQU 0x3778
CINEMATIC_093		EQU 0x3994
CINEMATIC_094		EQU 0x39E0
CINEMATIC_095		EQU 0x3944
CINEMATIC_096		EQU 0x37C4
CINEMATIC_097		EQU 0x42A4
CINEMATIC_098		EQU 0x42E8
CINEMATIC_099		EQU 0x432C
CINEMATIC_100		EQU 0x4370
CINEMATIC_101		EQU 0x3FE0
CINEMATIC_102		EQU 0x408C
CINEMATIC_103		EQU 0x4138
CINEMATIC_104		EQU 0x41E4
CINEMATIC_105		EQU 0x43CC
CINEMATIC_106		EQU 0x4728
CINEMATIC_107		EQU 0x477E
CINEMATIC_108		EQU 0x000C
COMMON_VIDEO_129		EQU 0x1B14
COMMON_VIDEO_168		EQU 0x181C
COMMON_VIDEO_169		EQU 0x1A84
COMMON_VIDEO_171		EQU 0x1866
COMMON_VIDEO_172		EQU 0x18B0
COMMON_VIDEO_173		EQU 0x1AB4
COMMON_VIDEO_175		EQU 0x18FA
COMMON_VIDEO_176		EQU 0x1AE4
COMMON_VIDEO_178		EQU 0x1944
COMMON_VIDEO_180		EQU 0x198E
COMMON_VIDEO_181		EQU 0x1B44
COMMON_VIDEO_184		EQU 0x19C4
COMMON_VIDEO_185		EQU 0x1B74
COMMON_VIDEO_188		EQU 0x1A0E
COMMON_VIDEO_189		EQU 0x1BA4
COMMON_VIDEO_192		EQU 0x1D78
COMMON_VIDEO_193		EQU 0x1BD4
COMMON_VIDEO_195		EQU 0x1D9A
COMMON_VIDEO_196		EQU 0x1DBC
COMMON_VIDEO_197		EQU 0x1DDE
COMMON_VIDEO_198		EQU 0x1E00
COMMON_VIDEO_199		EQU 0x1E22
COMMON_VIDEO_200		EQU 0x1E44
COMMON_VIDEO_201		EQU 0x1E66
COMMON_VIDEO_202		EQU 0x1A54
COMMON_VIDEO_291		EQU 0x4346
COMMON_VIDEO_301		EQU 0x1C78


	org 0x0000

LABEL_0000:
	call LABEL_0B35
	setup channel=0x3C, address=LABEL_0ACC
	mov [PAUSE_SLICES], 0x0004
	break
	song id=0x0000, delay=0x0000, pos=0x00
	call PRELOAD_RESOURCES_8_TO_1
	call LIKELY_A_COPY_PROTECTION_MECHANISM
	setup channel=0x1E, address=LABEL_0662
	killChannel
	copyVideoPage src=0x00, dst=0x03
	killChannel
	copyVideoPage src=0x03, dst=0x00

LABEL_0024:
	killChannel

LIKELY_A_COPY_PROTECTION_MECHANISM:
	jne [0xF2], 0x0FA0, DELETE_ALL_CHANS_AND_KILL
	ret

DELETE_ALL_CHANS_AND_KILL:
	deleteChannels first=0x00, last=0x3F
	killChannel

PRELOAD_RESOURCES_8_TO_1:
	load id=0x0008
	load id=0x008A
	load id=0x0081
	load id=0x0082
	load id=0x0083
	load id=0x0080
	load id=0x0001
	load id=0x0057
	load id=0x005E
	load id=0x000E
	load id=0x000F
	load id=0x005F
	load id=0x000C
	ret

LABEL_005A:
	video offset=CINEMATIC_097, x=160, y=100
	break
	video offset=CINEMATIC_098, x=160, y=100
	break
	video offset=CINEMATIC_099, x=160, y=100
	break
	video offset=CINEMATIC_100, x=160, y=100
	break
	video offset=CINEMATIC_099, x=160, y=100
	break
	video offset=CINEMATIC_098, x=160, y=100
	break
	jmp LABEL_005A
LABEL_007B:
	db 0x11

DRAW_CIN_101_102_FADE_PAL_C:
	video offset=CINEMATIC_101, x=160, y=125
	setPalette 0x0C
	break
	video offset=CINEMATIC_101, x=160, y=118
	break
	video offset=CINEMATIC_102, x=160, y=112
	break
	video offset=CINEMATIC_103, x=160, y=107
	break
	video offset=CINEMATIC_104, x=160, y=105
	break
	video offset=CINEMATIC_104, x=160, y=109
	break
	video offset=CINEMATIC_104, x=160, y=110
	break
	video offset=CINEMATIC_103, x=160, y=115

LABEL_00A6:
	break
	video offset=CINEMATIC_103, x=160, y=118
	jmp LABEL_00A6
LABEL_00AE:
	db 0x11

LABEL_00AF:
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	mov [0x03], 0x0040
	video offset=CINEMATIC_052, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_053, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_054, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_055, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_056, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_054, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_057, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_053, x=[0x01], y=[0x02], zoom=[0x03]
	deleteChannels first=0x0A, last=0x0E
	copyVideoPage src=0x03, dst=0x00
	setup channel=0x0A, address=LABEL_0149
	setup channel=0x0B, address=LABEL_010A
	setup channel=0x0E, address=LABEL_04F0
	setup channel=0x0F, address=LABEL_0115
	killChannel

LABEL_010A:
	video offset=CINEMATIC_058, x=160, y=100, zoom=[0x04]
	break
	jmp LABEL_010A
LABEL_0114:
	db 0x11

LABEL_0115:
	video offset=CINEMATIC_059, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_060, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_061, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_062, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_063, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_064, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_065, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_0115

LABEL_0149:
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	mov [0x03], 0x0040
	mov [0x04], 0x0040
	setPalette 0x0B
	add [0x04], 0x0002
	video offset=CINEMATIC_067, x=[0x01], y=[0x02], zoom=[0x03]
	break
	add [0x04], 0x0005
	video offset=CINEMATIC_068, x=[0x01], y=[0x02], zoom=[0x03]
	break
	add [0x04], 0x0008
	video offset=CINEMATIC_069, x=[0x01], y=[0x02], zoom=[0x03]
	setup channel=0x0C, address=LABEL_04FE
	setup channel=0x0D, address=LABEL_0579
	mov [0x06], 0x000A

LABEL_0188:
	break
	add [0x04], 0x000A
	djnz [0x06], LABEL_0188
	setup channel=0x0B, address=LABEL_0024
	mov [0x06], 0x0030

LABEL_0199:
	break
	sub [0x03], 0x0001
	djnz [0x06], LABEL_0199
	setup channel=0x10, address=INIT_VARE_TO_12
	setup channel=0x11, address=LABEL_0220
	mov [0x0F], 0x0001
	mov [0x06], 0x000C

LABEL_01B2:
	break
	break
	sub [0x03], 0x0001
	djnz [0x06], LABEL_01B2
	mov [0x06], 0x0019

LABEL_01C0:
	break
	djnz [0x06], LABEL_01C0
	sub [0x03], 0x0001
	mov [0x06], 0x0019

LABEL_01CD:
	break
	djnz [0x06], LABEL_01CD
	sub [0x03], 0x0001
	killChannel

INIT_VARE_TO_12:
	mov [0x0E], 0x000C

LABEL_01DB:
	break
	add [0x0F], 0x0001
	djnz [0x0E], LABEL_01DB
	mov [0x0E], 0x0009

LABEL_01E8:
	break
	add [0x0F], 0x0004
	djnz [0x0E], LABEL_01E8
	mov [0x0E], 0x0032

LABEL_01F5:
	break
	djnz [0x0E], LABEL_01F5
	mov [0x0E], 0x0005

LABEL_01FE:
	break
	add [0x0F], 0x0008
	djnz [0x0E], LABEL_01FE
	setup channel=0x36, address=LABEL_022B
	break
	add [0x0F], 0x000C
	break
	add [0x0F], 0x0018
	break
	add [0x0F], 0x0026
	break
	add [0x0F], 0x0038
	killChannel

LABEL_0220:
	video offset=CINEMATIC_070, x=[0x01], y=[0x02], zoom=[0x0f]
	break
	jmp LABEL_0220
LABEL_022A:
	db 0x11

LABEL_022B:
	setPalette 0x10
	break
	setPalette 0x11
	break
	setPalette 0x12
	break
	setPalette 0x13
	break
	setPalette 0x14
	break
	setPalette 0x15
	break
	setPalette 0x16
	break
	setPalette 0x17
	deleteChannels first=0x0A, last=0x11
	fill page=0x00, color=0x00
	fill page=0x03, color=0x00
	break
	jne [0xDB], 0x00, LABEL_034A
	selectVideoPage 0x00
	text id=0x0258, x=2, y=10, color=0x0C ; "      Designed by ..... Eric Chahi"
	text id=0x0259, x=2, y=40, color=0x0C ; "    Programmed by...... Eric Chahi"
	text id=0x025A, x=2, y=70, color=0x0C ; "      Artwork ......... Eric Chahi"
	text id=0x025B, x=1, y=100, color=0x0C ; "Music by ........ Jean-francois Freitas"
	text id=0x025C, x=2, y=130, color=0x0C ; "            Sound effects"
	text id=0x025D, x=2, y=140, color=0x0C ; "        Jean-Francois Freitas\n             Eric Chahi"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	setup channel=0x3C, address=LABEL_0ADF
	mov [PAUSE_SLICES], 0x0002
	mov [0x01], 0x000A

LABEL_0293:
	break
	djnz [0x01], LABEL_0293
	setup channel=0x14, address=PAL_FADE_18_TO_1D
	mov [0x01], 0x00AF

LABEL_02A0:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02A0
	mov [0x01], 0x00C8

LABEL_02AD:
	break
	djnz [0x01], LABEL_02AD
	mov [0x01], 0x00B4

LABEL_02B6:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02B6
	selectVideoPage 0x00
	fill page=0x00, color=0x00
	text id=0x0263, x=6, y=0, color=0x0C ; "              Thanks To"
	text id=0x0264, x=6, y=30, color=0x0C ; "           Jesus Martinez\n\n          Daniel Morais\n\n        Frederic Savoir\n\n      Cecile Chahi\n\n    Philippe Delamarre\n\n  Philippe Ulrich\n\nSebastien Berthet\n\nPierre Gousseau"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	mov [0x01], 0x0096

LABEL_02DA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02DA
	mov [0x01], 0x00C8

LABEL_02E7:
	break
	djnz [0x01], LABEL_02E7
	mov [0x01], 0x00C8

LABEL_02F0:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02F0
	selectVideoPage 0x00
	fill page=0x00, color=0x00
	text id=0x0265, x=6, y=0, color=0x0C ; "Now Go Out Of This World"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	mov [0x01], 0x0064

LABEL_030E:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_030E
	mov [0x01], 0x00AA

LABEL_031B:
	break
	djnz [0x01], LABEL_031B
	song id=0x0000, delay=0x0000, pos=0x00
	killChannel
	selectVideoPage 0x00
	text id=0x017C, x=9, y=10, color=0x0C ; "string_017C"
	text id=0x017D, x=19, y=40, color=0x05 ; "string_017D"
	text id=0x017E, x=13, y=90, color=0x0B ; "string_017E"
	text id=0x0180, x=12, y=120, color=0x0D ; "string_0180"
	text id=0x017F, x=12, y=150, color=0x0E ; "string_017F"
	selectVideoPage 0xFF
	killChannel

LABEL_034A:
	selectVideoPage 0x03
	text id=0x0258, x=2, y=20, color=0x0C ; "      Designed by ..... Eric Chahi"
	text id=0x0259, x=2, y=50, color=0x0C ; "    Programmed by...... Eric Chahi"
	text id=0x025A, x=2, y=80, color=0x0C ; "      Artwork ......... Eric Chahi"
	text id=0x025B, x=2, y=130, color=0x0C ; "Music by ........ Jean-francois Freitas"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x0000
	setup channel=0x3C, address=LABEL_0AED
	mov [PAUSE_SLICES], 0x0002
	mov [0x01], 0x000A

LABEL_0376:
	break
	djnz [0x01], LABEL_0376
	setup channel=0x14, address=PAL_FADE_18_TO_1D
	mov [0x01], 0x00C8

LABEL_0383:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0383
	selectVideoPage 0x00
	text id=0x025C, x=2, y=2, color=0x0C ; "            Sound effects"
	text id=0x025E, x=2, y=82, color=0x0C ; "string_025E"
	text id=0x025F, x=2, y=162, color=0x0C ; "string_025F"
	selectVideoPage 0xFF
	mov [0x01], 0x00C8

LABEL_03A6:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03A6
	fill page=0x03, color=0x00
	selectVideoPage 0x03
	text id=0x0260, x=2, y=45, color=0x0C ; "string_0260"
	text id=0x0261, x=2, y=172, color=0x0C ; "string_0261"
	selectVideoPage 0xFF
	mov [0x01], 0x00C8

LABEL_03C6:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03C6
	fill page=0x00, color=0x00
	mov [0x01], 0x00C8

LABEL_03D6:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03D6
	fill page=0x03, color=0x00
	selectVideoPage 0x03
	text id=0x0263, x=5, y=50, color=0x0C ; "              Thanks To"
	text id=0x0264, x=2, y=90, color=0x0C ; "           Jesus Martinez\n\n          Daniel Morais\n\n        Frederic Savoir\n\n      Cecile Chahi\n\n    Philippe Delamarre\n\n  Philippe Ulrich\n\nSebastien Berthet\n\nPierre Gousseau"
	selectVideoPage 0xFF
	sub [SCROLL_Y], 0x0032
	mov [0x01], 0x0096

LABEL_03FA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03FA
	mov [0x01], 0x0028

LABEL_0407:
	break
	djnz [0x01], LABEL_0407
	fill page=0x00, color=0x00
	mov [0x01], 0x00BE

LABEL_0413:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0413
	sub [SCROLL_Y], 0x000A
	selectVideoPage 0x03
	fill page=0x03, color=0x00
	text id=0x0265, x=6, y=0, color=0x0C ; "Now Go Out Of This World"
	selectVideoPage 0xFF
	mov [0x01], 0x0064

LABEL_0431:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0431
	mov [0x01], 0x0096

LABEL_043E:
	break
	djnz [0x01], LABEL_043E
	song id=0x0000, delay=0x0000, pos=0x00
	killChannel
	killChannel

PAL_FADE_18_TO_1D:
	setPalette 0x18
	break
	setPalette 0x19
	break
	setPalette 0x1A
	break
	setPalette 0x1B
	break
	setPalette 0x1C
	break
	setPalette 0x1D
	killChannel
	setPalette 0x1D
	break
	setPalette 0x1C
	break
	setPalette 0x1B
	break
	setPalette 0x1A
	break
	setPalette 0x19
	break
	setPalette 0x18
	break
	setPalette 0x17
	killChannel

DRAW_CIN_71_72_FADE:
	video offset=CINEMATIC_071, x=160, y=100
	break
	video offset=CINEMATIC_071, x=160, y=100
	break
	video offset=CINEMATIC_071, x=160, y=100
	break
	video offset=CINEMATIC_072, x=160, y=100
	break
	video offset=CINEMATIC_072, x=160, y=100
	break
	video offset=CINEMATIC_073, x=160, y=100
	break
	video offset=CINEMATIC_073, x=160, y=100

LABEL_04A1:
	break
	video offset=CINEMATIC_074, x=160, y=100
	jmp LABEL_04A1
LABEL_04A9:
	db 0x06

LABEL_04AA:
	video offset=CINEMATIC_071, x=160, y=100
	break
	jmp LABEL_04AA

DRAW_CIN_106_107_FX_57:
	video offset=CINEMATIC_106, x=160, y=100
	break
	video offset=CINEMATIC_106, x=160, y=100
	break
	play id=0x0057, freq=0x22, vol=0x20, channel=0x03
	video offset=CINEMATIC_107, x=160, y=100
	break
	video offset=CINEMATIC_107, x=160, y=100
	break
	video offset=CINEMATIC_107, x=160, y=100
	break
	video offset=CINEMATIC_107, x=160, y=100
	break
	video offset=CINEMATIC_106, x=160, y=100

LABEL_04DA:
	break
	video offset=CINEMATIC_074, x=160, y=100
	jmp LABEL_04DA
LABEL_04E2:
	db 0x11

LABEL_04E3:
	video offset=CINEMATIC_105, x=160, y=100
	add [0x03], 0x0002
	break
	jmp LABEL_04E3
LABEL_04EF:
	db 0x11

LABEL_04F0:
	video offset=CINEMATIC_066, x=[0x01], y=[0x02], zoom=[0x03]
	add [0x03], 0x0000
	break
	jmp LABEL_04F0

LABEL_04FE:
	video offset=CINEMATIC_086, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_087, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_088, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_089, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_090, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_091, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_092, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_093, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_094, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_092, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_091, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_090, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_089, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_088, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_087, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_095, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_096, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_04FE
LABEL_0578:
	db 0x11

LABEL_0579:
	video offset=CINEMATIC_075, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_076, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_077, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_078, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_079, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_080, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_081, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_082, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_083, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_081, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_080, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_079, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_078, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_077, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_076, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_084, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video offset=CINEMATIC_085, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_0579
LABEL_05F3:
	db 0x11

SET_VAR_E6_5_PAL_B:
	mov [0xE6], 0x0005
	setPalette 0x0B

LABEL_05FB:
	video offset=CINEMATIC_042, x=160, y=100
	break
	djnz [0xE6], LABEL_05FB
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	video offset=CINEMATIC_043, x=160, y=100
	break
	video offset=CINEMATIC_044, x=160, y=100
	break
	video offset=CINEMATIC_045, x=160, y=100
	break
	video offset=CINEMATIC_046, x=160, y=100
	mov [0xE6], 0x0007

LABEL_0621:
	break
	video offset=CINEMATIC_046, x=160, y=100
	djnz [0xE6], LABEL_0621
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	break
	video offset=CINEMATIC_047, x=160, y=100
	break
	video offset=CINEMATIC_048, x=160, y=100
	break
	video offset=CINEMATIC_049, x=160, y=100
	break
	video offset=CINEMATIC_050, x=160, y=100
	mov [0xE6], 0x000A

LABEL_0648:
	break
	video offset=CINEMATIC_051, x=160, y=100
	djnz [0xE6], LABEL_0648
	setup channel=0x0A, address=LABEL_04E3
	setup channel=0x0B, address=DRAW_CIN_101_102_FADE_PAL_C
	setup channel=0x0C, address=LABEL_005A
	setup channel=0x0D, address=LABEL_00AF
	killChannel

LABEL_0662:
	call DRAW_STARS_PAGE0_CIN_000
	call DRAW_STARS_PAGE3_CIN_004
	setup channel=0x05, address=LABEL_04AA
	selectVideoPage 0x00
	play id=0x0008, freq=0x05, vol=0x20, channel=0x00
	play id=0x0008, freq=0x07, vol=0x30, channel=0x01
	video offset=CINEMATIC_008, x=160, y=100
	video offset=CINEMATIC_009, x=160, y=100
	video offset=CINEMATIC_010, x=160, y=100
	selectVideoPage 0xFF
	mov [PAUSE_SLICES], 0x0004
	mov [0x03], 0x000A
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	setPalette 0x0A

LABEL_069B:
	break
	djnz [0x03], LABEL_069B
	setup channel=0x05, address=DRAW_CIN_71_72_FADE
	video offset=CINEMATIC_011, x=[0x01], y=[0x02], zoom=0x40
	play id=0x0008, freq=0x0A, vol=0x16, channel=0x00
	play id=0x0057, freq=0x14, vol=0x20, channel=0x02
	break
	video offset=CINEMATIC_012, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_013, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	play id=0x000E, freq=0x03, vol=0x20, channel=0x03
	mov [0x03], 0x0014

LABEL_06D1:
	break
	video offset=CINEMATIC_015, x=[0x01], y=[0x02], zoom=0x40
	djnz [0x03], LABEL_06D1
	mov [PAUSE_SLICES], 0x000A
	mov [0x03], 0x0006
	play id=0x000F, freq=0x03, vol=0x30, channel=0x03
	break
	play id=0x0008, freq=0x07, vol=0x11, channel=0x01

LABEL_06F0:
	video offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	jne [0x03], 0x04, LABEL_070E
	song id=0x008A, delay=0x3A98, pos=0x00
	play id=0x0008, freq=0x0A, vol=0x16, channel=0x00

LABEL_070E:
	jne [0x03], 0x03, LABEL_071A
	play id=0x0008, freq=0x0A, vol=0x0B, channel=0x00

LABEL_071A:
	video offset=CINEMATIC_013, x=[0x01], y=[0x02], zoom=0x40
	break
	add [0x01], 0x0002
	video offset=CINEMATIC_016, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_016, x=[0x01], y=[0x02], zoom=0x40
	break
	add [0x01], 0x0001
	video offset=CINEMATIC_017, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_017, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_015, x=[0x01], y=[0x02], zoom=0x40
	break
	video offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	add [PAUSE_SLICES], 0x0002
	djnz [0x03], LABEL_06F0
	mov [PAUSE_SLICES], 0x0006
	video offset=CINEMATIC_019, x=[0x01], y=[0x02], zoom=0x40
	setup channel=0x14, address=INIT_VARS_07_08_09

LABEL_0773:
	break
	video offset=CINEMATIC_020, x=[0x01], y=[0x02], zoom=0x40
	jmp LABEL_0773
LABEL_077C:
	db 0x11

INIT_VARS_07_08_09:
	mov [0x07], 0x004C
	mov [0x08], 0x0097
	mov [0x09], 0x0003

LABEL_0789:
	break
	djnz [0x09], LABEL_0789
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	video offset=CINEMATIC_021, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_022, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_023, x=[0x07], y=[0x08], zoom=0x40
	mov [0x09], 0x000A

LABEL_07A9:
	break
	video offset=CINEMATIC_024, x=[0x07], y=[0x08], zoom=0x40
	video offset=CINEMATIC_025, x=[0x07], y=[0x08], zoom=0x40
	djnz [0x09], LABEL_07A9
	setup channel=0x11, address=LABEL_084A
	setup channel=0x12, address=LABEL_0854
	setup channel=0x13, address=LABEL_08B8
	setup channel=0x0C, address=LABEL_091C
	mov [0x09], 0x0010

LABEL_07CC:
	break
	djnz [0x09], LABEL_07CC
	setup channel=0x0C, address=LABEL_0024
	deleteChannels first=0x11, last=0x13
	break
	video offset=CINEMATIC_026, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_027, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_028, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_029, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_030, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_031, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x05, address=DRAW_CIN_106_107_FX_57
	mov [0x09], 0x000A

LABEL_0805:
	break
	video offset=CINEMATIC_032, x=[0x07], y=[0x08], zoom=0x40
	djnz [0x09], LABEL_0805
	setup channel=0x1E, address=LABEL_0024
	break
	video offset=CINEMATIC_033, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_034, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_035, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_036, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=0x40
	break
	video offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=0x40
	selectVideoPage 0x00
	fill page=0x00, color=0x01
	call DRAW_STARS_CIN_38_39_40_5_6
	selectVideoPage 0xFF
	setup channel=0x05, address=LABEL_0024
	setup channel=0x0A, address=SET_VAR_E6_5_PAL_B
	killChannel

LABEL_084A:
	video offset=CINEMATIC_024, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_084A
LABEL_0853:
	db 0x11

LABEL_0854:
	video type=0, offset=COMMON_VIDEO_192, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_195, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_196, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_197, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_198, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_199, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_200, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_201, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_168, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_171, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_172, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_175, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_178, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_180, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_184, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_188, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_0854
LABEL_08B7:
	db 0x11

LABEL_08B8:
	video type=0, offset=COMMON_VIDEO_193, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_185, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_181, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_129, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_176, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_173, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_202, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_202, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_169, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_169, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_173, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_176, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_129, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_181, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_185, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_189, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_08B8
LABEL_091B:
	db 0x11

LABEL_091C:
	mov [0x0A], 0x0003
	add [0x07], 0x0002
	break
	djnz [0x0A], LABEL_091C
	mov [0x0A], 0x0005

LABEL_092D:
	add [0x07], 0x0003
	break
	djnz [0x0A], LABEL_092D
	jmp LABEL_091C
	killChannel
	video offset=CINEMATIC_108, x=160, y=100
	video type=0, offset=COMMON_VIDEO_301, x=160, y=100, zoom=0x40
	video type=0, offset=COMMON_VIDEO_291, x=160, y=100, zoom=0x40
	video type=0, offset=COMMON_VIDEO_202, x=160, y=100, zoom=0x40
	killChannel

DRAW_STARS_PAGE0_CIN_000:
	selectVideoPage 0x00
	fill page=0x00, color=0x01
	video offset=CINEMATIC_000, x=253, y=34, zoom=[0x0a]	;@enc=alt
	video offset=CINEMATIC_000, x=269, y=29, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=273, y=78, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=303, y=57, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=140, y=79, zoom=[0x08]	;@enc=alt
	video offset=CINEMATIC_000, x=214, y=85, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=66, y=79, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=111, y=52, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_000, x=95, y=103, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=153, y=89, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=132, y=107, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=4, y=85, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_000, x=65, y=115, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_000, x=293, y=139, zoom=0x40
	video offset=CINEMATIC_000, x=11, y=109, zoom=[0x1c]	;@enc=alt
	video offset=CINEMATIC_000, x=11, y=146
	video offset=CINEMATIC_001, x=31, y=187
	video offset=CINEMATIC_002, x=301, y=14, zoom=0x40
	video offset=CINEMATIC_001, x=294, y=188, zoom=0x40
	video offset=CINEMATIC_003, x=2, y=167
	video offset=CINEMATIC_002, x=92, y=30
	video offset=CINEMATIC_002, x=128, y=11
	video offset=CINEMATIC_002, x=166, y=10
	video offset=CINEMATIC_002, x=85, y=19
	video offset=CINEMATIC_002, x=48, y=12
	video offset=CINEMATIC_002, x=111, y=3
	video offset=CINEMATIC_002, x=13, y=11, zoom=[0x20]	;@enc=alt
	selectVideoPage 0xFF
	ret
LABEL_09E3:
	db 0x11

DRAW_STARS_PAGE3_CIN_004:
	selectVideoPage 0x03
	fill page=0x03, color=0x01
	video offset=CINEMATIC_004, x=253, y=34, zoom=[0x0a]	;@enc=alt
	video offset=CINEMATIC_004, x=269, y=29, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=273, y=78, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=303, y=57, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=140, y=79, zoom=[0x08]	;@enc=alt
	video offset=CINEMATIC_004, x=214, y=85, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=66, y=79, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=111, y=52, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_004, x=95, y=103, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=153, y=89, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=132, y=107, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=4, y=85, zoom=[0x10]	;@enc=alt
	video offset=CINEMATIC_004, x=65, y=115, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_004, x=293, y=139, zoom=0x40
	video offset=CINEMATIC_004, x=11, y=109, zoom=[0x1c]	;@enc=alt
	video offset=CINEMATIC_004, x=11, y=146
	video offset=CINEMATIC_005, x=31, y=187
	video offset=CINEMATIC_006, x=301, y=14, zoom=0x40
	video offset=CINEMATIC_005, x=294, y=188, zoom=0x40
	video offset=CINEMATIC_007, x=2, y=167
	video offset=CINEMATIC_006, x=92, y=30
	video offset=CINEMATIC_006, x=128, y=11
	video offset=CINEMATIC_006, x=166, y=10
	video offset=CINEMATIC_006, x=85, y=19
	video offset=CINEMATIC_006, x=48, y=12
	video offset=CINEMATIC_006, x=111, y=3
	video offset=CINEMATIC_006, x=13, y=11, zoom=[0x20]	;@enc=alt
	selectVideoPage 0xFF
	ret
LABEL_0A79:
	db 0x11

DRAW_STARS_CIN_38_39_40_5_6:
	video offset=CINEMATIC_006, x=126, y=25
	video offset=CINEMATIC_038, x=133, y=102, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_038, x=129, y=114, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_038, x=114, y=126, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_006, x=91, y=8, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_039, x=16, y=114
	video offset=CINEMATIC_039, x=74, y=177, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_040, x=78, y=166
	video offset=CINEMATIC_005, x=283, y=175, zoom=0x40
	video offset=CINEMATIC_005, x=294, y=183, zoom=0x40
	video offset=CINEMATIC_005, x=58, y=185
	video offset=CINEMATIC_005, x=5, y=170
	video offset=CINEMATIC_041, x=197, y=160, zoom=[0x20]	;@enc=alt
	video offset=CINEMATIC_041, x=61, y=169
	video offset=CINEMATIC_041, x=300, y=28, zoom=0x40
	video offset=CINEMATIC_041, x=202, y=86, zoom=[0x30]	;@enc=alt
	ret

LABEL_0ACC:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	break
	jmp LABEL_0ACC

JUNK__0AD7:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	break
	jmp JUNK__0AD7

LABEL_0ADF:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	fill page=0xFF, color=0x00
	copyVideoPage src=0x80, dst=0xFF
	break
	jmp LABEL_0ADF

LABEL_0AED:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	jg [SCROLL_Y], 0xFF38, LABEL_0AFF
	add [SCROLL_Y], 0x00C8
	jmp LABEL_0B23

LABEL_0AFF:
	copyVideoPage src=0x80, dst=0xFF
	add [SCROLL_Y], 0x00C8
	copyVideoPage src=0x83, dst=0xFF
	sub [SCROLL_Y], 0x00C8
	break
	jmp LABEL_0AED

LABEL_0B11:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	jg [SCROLL_Y], 0xFF38, LABEL_0B23
	add [SCROLL_Y], 0x00C8
	jmp LABEL_0AFF

LABEL_0B23:
	copyVideoPage src=0x83, dst=0xFF
	add [SCROLL_Y], 0x00C8
	copyVideoPage src=0x80, dst=0xFF
	sub [SCROLL_Y], 0x00C8
	break
	jmp LABEL_0B11

LABEL_0B35:
	fill page=0x01, color=0x00
	fill page=0x02, color=0x00
	selectVideoPage 0x01
	blitFramebuffer 0x01
	blitFramebuffer 0xFF
	blitFramebuffer 0x02
	ret
LABEL_0B44:
	db 0x11, 0x11, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
	FILL(62644, 0xFF)
