; STAGE PASSCODE: password-entry screen for save-state restoration.
;
; Gameplay role: shown before the game starts (or between sessions)
; to let players resume from a stored checkpoint. Hashes the entered
; characters into per-stage save vectors. Replaces the checkpoint
; system on platforms without battery-backed save.
;
; This file: dos_1992 (Daniel Morais MS-DOS port)
;
;
; Smallest unified file (only 6 folded bodies). The hashing logic
; (SUM_HASH_VARS_TO_VAR_37) is one of the most analyzed routines
; in the genealogy work — it's structurally identical across all
; three branches.
;
; Generated by AnotherWorld_VMTools
;@include "../_common_vars.inc"
CINEMATIC_000		EQU 0x104C
CINEMATIC_001		EQU 0x1040
CINEMATIC_002		EQU 0x1034
CINEMATIC_003		EQU 0x1028
CINEMATIC_004		EQU 0x1010
CINEMATIC_005		EQU 0x101C
CINEMATIC_006		EQU 0x1004
CINEMATIC_007		EQU 0x0FB4
CINEMATIC_008		EQU 0x0FF4
CINEMATIC_009		EQU 0x0FC4
CINEMATIC_010		EQU 0x0FD4
CINEMATIC_011		EQU 0x0FE4
CINEMATIC_012		EQU 0x0FA4
CINEMATIC_013		EQU 0x0F94
CINEMATIC_014		EQU 0x0F84
CINEMATIC_015		EQU 0x0F74
CINEMATIC_016		EQU 0x0F64
CINEMATIC_017		EQU 0x1364
CINEMATIC_018		EQU 0x1394
CINEMATIC_019		EQU 0x130C
CINEMATIC_020		EQU 0x1344
CINEMATIC_021		EQU 0x12D8
CINEMATIC_022		EQU 0x0CFC
CINEMATIC_023		EQU 0x12C0
CINEMATIC_024		EQU 0x128C
CINEMATIC_025		EQU 0x1258
CINEMATIC_026		EQU 0x1234
CINEMATIC_027		EQU 0x1208
CINEMATIC_028		EQU 0x0CD0
CINEMATIC_029		EQU 0x0C9C
CINEMATIC_030		EQU 0x11E8
CINEMATIC_031		EQU 0x11C8
CINEMATIC_032		EQU 0x0D30
CINEMATIC_033		EQU 0x11A4
CINEMATIC_034		EQU 0x0D14
CINEMATIC_035		EQU 0x1174
CINEMATIC_036		EQU 0x0D80
CINEMATIC_037		EQU 0x097C
CINEMATIC_038		EQU 0x091C
CINEMATIC_039		EQU 0x0D58
CINEMATIC_040		EQU 0x114C
CINEMATIC_041		EQU 0x1124
CINEMATIC_042		EQU 0x10EC
CINEMATIC_043		EQU 0x10B8
CINEMATIC_044		EQU 0x1080
CINEMATIC_045		EQU 0x1054
CINEMATIC_046		EQU 0x0DEC
CINEMATIC_047		EQU 0x0E44
CINEMATIC_048		EQU 0x0E80
CINEMATIC_049		EQU 0x0E18
CINEMATIC_050		EQU 0x0DC0
CINEMATIC_051		EQU 0x0F30
CINEMATIC_052		EQU 0x0EB4
CINEMATIC_053		EQU 0x0EF0
CINEMATIC_054		EQU 0x0DA4
CINEMATIC_055		EQU 0x08C4
CINEMATIC_056		EQU 0x0908
CINEMATIC_057		EQU 0x000C
CINEMATIC_058		EQU 0x0020


	org 0x0000

LABEL_0000:
	call LABEL_1090
	mov [PAUSE_SLICES], 0x0002
	setup channel=0x3C, address=LABEL_107D
	fill page=0x00, color=0x00
	fill page=0xFF, color=0x00
	mov [LAST_KEYCHAR], 0x0000
	break
	setPalette 0x05
	fill page=0x00, color=0x00
	setup channel=0x14, address=SETUP_PASSCODE_SCREEN
	killChannel

KILL_CHAN_AT_0021:
	killChannel

INDEX_VAR06_BY_VAR05:
	jne [0x05], 0x00, LOAD_VAR0B_TO_VAR06
	mov [0x06], [0x0A]

LOAD_VAR0B_TO_VAR06:
	jne [0x05], 0x01, LOAD_VAR0C_TO_VAR06
	mov [0x06], [0x0B]

LOAD_VAR0C_TO_VAR06:
	jne [0x05], 0x02, LOAD_VAR0D_TO_VAR06
	mov [0x06], [0x0C]

LOAD_VAR0D_TO_VAR06:
	jne [0x05], 0x03, LOAD_VAR0E_TO_VAR06
	mov [0x06], [0x0D]

LOAD_VAR0E_TO_VAR06:
	jne [0x05], 0x04, LOAD_VAR0F_TO_VAR06
	mov [0x06], [0x0E]

LOAD_VAR0F_TO_VAR06:
	jne [0x05], 0x05, LOAD_VAR10_TO_VAR06
	mov [0x06], [0x0F]

LOAD_VAR10_TO_VAR06:
	jne [0x05], 0x06, LOAD_VAR11_TO_VAR06
	mov [0x06], [0x10]

LOAD_VAR11_TO_VAR06:
	jne [0x05], 0x07, LOAD_VAR12_TO_VAR06
	mov [0x06], [0x11]

LOAD_VAR12_TO_VAR06:
	jne [0x05], 0x08, LOAD_VAR13_TO_VAR06
	mov [0x06], [0x12]

LOAD_VAR13_TO_VAR06:
	jne [0x05], 0x09, LOAD_VAR14_TO_VAR06
	mov [0x06], [0x13]

LOAD_VAR14_TO_VAR06:
	jne [0x05], 0x0A, LOAD_VAR15_TO_VAR06
	mov [0x06], [0x14]

LOAD_VAR15_TO_VAR06:
	jne [0x05], 0x0B, LOAD_VAR16_TO_VAR06
	mov [0x06], [0x15]

LOAD_VAR16_TO_VAR06:
	jne [0x05], 0x0C, LOAD_VAR17_TO_VAR06
	mov [0x06], [0x16]

LOAD_VAR17_TO_VAR06:
	jne [0x05], 0x0D, LOAD_VAR18_TO_VAR06
	mov [0x06], [0x17]

LOAD_VAR18_TO_VAR06:
	jne [0x05], 0x0E, LOAD_VAR19_TO_VAR06
	mov [0x06], [0x18]

LOAD_VAR19_TO_VAR06:
	jne [0x05], 0x0F, SHARED_RET
	mov [0x06], [0x19]
	ret

SETUP_PASSCODE_SCREEN:
	mov [0x09], 0x0010
	fill page=0xFF, color=0x00
	mov [0x04], 0x0040
	mov [0x02], 0x0000
	mov [0x05], [0x37]
	and [0x05], 0x000F
	mov [0x2F], [0x05]
	call INIT_PASSCODE_LETTER_ALPHABET
	mov [0x2D], 0x0072
	mov [0x2E], 0x003E
	mov [0x19], 0x0062
	mov [0x11], 0x0063
	mov [0x1E], 0xFFFF
	mov [0x1F], 0xFFFF
	mov [0x20], 0xFFFF
	mov [0x21], 0xFFFF
	mov [0x05], 0x0000
	selectVideoPage 0x00
	text id=0x013E, x=4, y=70, color=0x00 ; "   ENTER ACCESS CODE"
	text id=0x013C, x=2, y=80, color=0x06 ; "        ACCESS CODE:"
	call COPY_PROTECTION_VAR_BC_C6
	selectVideoPage 0xFF

LABEL_0106:
	call INDEX_VAR06_BY_VAR05
	selectVideoPage 0x00
	call DERIVE_AND_DRAW_LETTER
	selectVideoPage 0xFF
	add [0x05], 0x0001
	djnz [0x09], LABEL_0106
	je [0xDB], 0x00, LABEL_012E
	selectVideoPage 0x00
	text id=0x012C, x=7, y=130, color=0x04 ; "0"
	text id=0x012D, x=7, y=146, color=0x04 ; "1"
	selectVideoPage 0xFF

LABEL_012E:
	mov [0x01], 0x0003
	mov [0x07], 0x00A0
	mov [0x08], 0x0064
	mov [0x05], [0x01]
	call DERIVE_VAR07_VAR08_FROM_VAR05
	jmp LABEL_0615
LABEL_0143:
	db 0x11

COPY_PROTECTION_VAR_BC_C6:
	and [0xBC], 0x0010
	and [0xC6], 0x0080
	jmp LIKELY_A_COPY_PROTECTION_MECHANISM
	je [0xBC], 0x00, DRAW_PROGRESS_MARKERS
	video offset=CINEMATIC_058, x=0, y=0

DRAW_PROGRESS_MARKERS:
	je [0xC6], 0x00, DRAW_CIN_058_AT_0_16_IF_VARF2_EQ_FA0
	video offset=CINEMATIC_058, x=16, y=0

DRAW_CIN_058_AT_0_16_IF_VARF2_EQ_FA0:
	jne [0xF2], 0x0FA0, DRAW_CIN_058_AT_16_16_IF_VARDC_EQ_21
	video offset=CINEMATIC_058, x=0, y=16

DRAW_CIN_058_AT_16_16_IF_VARDC_EQ_21:
	jne [HACK_VAR_DC], 0x21, TRIVIAL_RET
	video offset=CINEMATIC_058, x=16, y=16

TRIVIAL_RET:
	ret

LIKELY_A_COPY_PROTECTION_MECHANISM:
	je [0xBC], 0x00, PASSCODE_RESTART_OR_DRAW_CIN_016
	je [0xC6], 0x00, PASSCODE_RESTART_OR_DRAW_CIN_016
	jne [0xF2], 0x0FA0, PASSCODE_RESTART_OR_DRAW_CIN_016
	jne [HACK_VAR_DC], 0x21, PASSCODE_RESTART_OR_DRAW_CIN_016
	ret

PASSCODE_RESTART_OR_DRAW_CIN_016:
	deleteChannels first=0x00, last=0x3F
	setup channel=0x3C, address=KILL_CHAN_AT_0021
	killChannel
	jne [0x05], 0x00, DRAW_CIN_015_AT_2D_2E_KEY01
	video offset=CINEMATIC_016, x=[0x2d], y=[0x2e]

DRAW_CIN_015_AT_2D_2E_KEY01:
	jne [0x05], 0x01, DRAW_CIN_014_AT_2D_2E_KEY02
	video offset=CINEMATIC_015, x=[0x2d], y=[0x2e]

DRAW_CIN_014_AT_2D_2E_KEY02:
	jne [0x05], 0x02, DRAW_CIN_013_AT_2D_2E_KEY03
	video offset=CINEMATIC_014, x=[0x2d], y=[0x2e]

DRAW_CIN_013_AT_2D_2E_KEY03:
	jne [0x05], 0x03, DRAW_CIN_012_AT_2D_2E_KEY04
	video offset=CINEMATIC_013, x=[0x2d], y=[0x2e]

DRAW_CIN_012_AT_2D_2E_KEY04:
	jne [0x05], 0x04, DRAW_CIN_011_AT_2D_2E_KEY05
	video offset=CINEMATIC_012, x=[0x2d], y=[0x2e]

DRAW_CIN_011_AT_2D_2E_KEY05:
	jne [0x05], 0x05, DRAW_CIN_010_AT_2D_2E_KEY06
	video offset=CINEMATIC_011, x=[0x2d], y=[0x2e]

DRAW_CIN_010_AT_2D_2E_KEY06:
	jne [0x05], 0x06, DRAW_CIN_009_AT_2D_2E_KEY07
	video offset=CINEMATIC_010, x=[0x2d], y=[0x2e]

DRAW_CIN_009_AT_2D_2E_KEY07:
	jne [0x05], 0x07, DRAW_CIN_008_AT_2D_2E_KEY08
	video offset=CINEMATIC_009, x=[0x2d], y=[0x2e]

DRAW_CIN_008_AT_2D_2E_KEY08:
	jne [0x05], 0x08, DRAW_CIN_007_AT_2D_2E_KEY09
	video offset=CINEMATIC_008, x=[0x2d], y=[0x2e]

DRAW_CIN_007_AT_2D_2E_KEY09:
	jne [0x05], 0x09, DRAW_CIN_006_AT_2D_2E_KEY0A
	video offset=CINEMATIC_007, x=[0x2d], y=[0x2e]

DRAW_CIN_006_AT_2D_2E_KEY0A:
	jne [0x05], 0x0A, DRAW_CIN_005_AT_2D_2E_KEY0B
	video offset=CINEMATIC_006, x=[0x2d], y=[0x2e]

DRAW_CIN_005_AT_2D_2E_KEY0B:
	jne [0x05], 0x0B, DRAW_CIN_004_AT_2D_2E_KEY0C
	video offset=CINEMATIC_005, x=[0x2d], y=[0x2e]

DRAW_CIN_004_AT_2D_2E_KEY0C:
	jne [0x05], 0x0C, DRAW_CIN_003_AT_2D_2E_KEY0D
	video offset=CINEMATIC_004, x=[0x2d], y=[0x2e]

DRAW_CIN_003_AT_2D_2E_KEY0D:
	jne [0x05], 0x0D, DRAW_CIN_002_AT_2D_2E_KEY0E
	video offset=CINEMATIC_003, x=[0x2d], y=[0x2e]

DRAW_CIN_002_AT_2D_2E_KEY0E:
	jne [0x05], 0x0E, DRAW_CIN_001_AT_2D_2E_KEY0F
	video offset=CINEMATIC_002, x=[0x2d], y=[0x2e]

DRAW_CIN_001_AT_2D_2E_KEY0F:
	jne [0x05], 0x0F, DRAW_CIN_000_AT_2D_2E_KEY10
	video offset=CINEMATIC_001, x=[0x2d], y=[0x2e]

DRAW_CIN_000_AT_2D_2E_KEY10:
	jne [0x05], 0x10, SHARED_RET
	video offset=CINEMATIC_000, x=[0x2d], y=[0x2e]
	ret

INIT_PASSCODE_LETTER_ALPHABET:
	mov [0x2C], 0x0000
	mov [0x0A], 0x000B
	mov [0x0B], 0x000C
	mov [0x0C], 0x000D
	mov [0x0D], 0x000F
	mov [0x0E], 0x0010
	mov [0x0F], 0x0011
	mov [0x10], 0xFFFF
	mov [0x11], 0x0000
	mov [0x12], 0x0013
	mov [0x13], 0x0014
	mov [0x14], 0x0015
	mov [0x15], 0x001B
	mov [0x16], 0x001D
	mov [0x17], 0x0021
	mov [0x18], 0xFFFF
	mov [0x19], 0x0000
	ret
	jne [0x05], 0x00, SETUP_VAR29_2A_2B_KEY01
	mov [0x29], 0x0015
	mov [0x2A], 0x0009
	mov [0x2B], 0x0013

SETUP_VAR29_2A_2B_KEY01:
	jne [0x05], 0x01, SETUP_VAR29_2A_2B_KEY02
	mov [0x29], 0x0016
	mov [0x2A], 0x0009
	mov [0x2B], 0x0006

SETUP_VAR29_2A_2B_KEY02:
	jne [0x05], 0x02, SETUP_VAR29_2A_2B_KEY03
	mov [0x29], 0x0017
	mov [0x2A], 0x0006
	mov [0x2B], 0x0018

SETUP_VAR29_2A_2B_KEY03:
	jne [0x05], 0x03, SETUP_VAR29_2A_2B_KEY04
	mov [0x29], 0x0004
	mov [0x2A], 0x0010
	mov [0x2B], 0x0009

SETUP_VAR29_2A_2B_KEY04:
	jne [0x05], 0x04, SETUP_VAR29_2A_2B_KEY05
	mov [0x29], 0x000B
	mov [0x2A], 0x0015
	mov [0x2B], 0x0019

SETUP_VAR29_2A_2B_KEY05:
	jne [0x05], 0x05, SETUP_VAR29_2A_2B_KEY06
	mov [0x29], 0x0006
	mov [0x2A], 0x0017
	mov [0x2B], 0x0016

SETUP_VAR29_2A_2B_KEY06:
	jne [0x05], 0x06, SETUP_VAR29_2A_2B_KEY07
	mov [0x29], 0x0004
	mov [0x2A], 0x0009
	mov [0x2B], 0x0016

SETUP_VAR29_2A_2B_KEY07:
	jne [0x05], 0x07, SETUP_VAR29_2A_2B_KEY08
	mov [0x29], 0x001A
	mov [0x2A], 0x000B
	mov [0x2B], 0x0015

SETUP_VAR29_2A_2B_KEY08:
	jne [0x05], 0x08, SETUP_VAR29_2A_2B_KEY09
	mov [0x29], 0x0018
	mov [0x2A], 0x0006
	mov [0x2B], 0x0009

SETUP_VAR29_2A_2B_KEY09:
	jne [0x05], 0x09, SETUP_VAR29_2A_2B_KEY0A
	mov [0x29], 0x0017
	mov [0x2A], 0x001C
	mov [0x2B], 0x0001

SETUP_VAR29_2A_2B_KEY0A:
	jne [0x05], 0x0A, SETUP_VAR29_2A_2B_KEY0B
	mov [0x29], 0x0006
	mov [0x2A], 0x0009
	mov [0x2B], 0x0010

SETUP_VAR29_2A_2B_KEY0B:
	jne [0x05], 0x0B, SETUP_VAR29_2A_2B_KEY0C
	mov [0x29], 0x0019
	mov [0x2A], 0x001B
	mov [0x2B], 0x000B

SETUP_VAR29_2A_2B_KEY0C:
	jne [0x05], 0x0C, SETUP_VAR29_2A_2B_KEY0D
	mov [0x29], 0x0006
	mov [0x2A], 0x0017
	mov [0x2B], 0x0001

SETUP_VAR29_2A_2B_KEY0D:
	jne [0x05], 0x0D, SETUP_VAR29_2A_2B_KEY0E
	mov [0x29], 0x001C
	mov [0x2A], 0x0016
	mov [0x2B], 0x0009

SETUP_VAR29_2A_2B_KEY0E:
	jne [0x05], 0x0E, SETUP_VAR29_2A_2B_KEY0F
	mov [0x29], 0x000B
	mov [0x2A], 0x001A
	mov [0x2B], 0x0015

SETUP_VAR29_2A_2B_KEY0F:
	jne [0x05], 0x0F, SETUP_VAR29_2A_2B_KEY10
	mov [0x29], 0x000A
	mov [0x2A], 0x0015
	mov [0x2B], 0x0013

SETUP_VAR29_2A_2B_KEY10:
	jne [0x05], 0x10, SHARED_RET
	mov [0x29], 0x000D
	mov [0x2A], 0x000A
	mov [0x2B], 0x0007
	mov [0x2C], 0x001D
	ret
	mov [0x0A], [0x29]
	mov [0x0C], [0x2A]
	mov [0x14], [0x2B]
	mov [0x17], [0x2C]
	ret
	mov [0x21], 0x0000

LABEL_03E5:
	je [0x21], 0x07, LABEL_0406
	je [0x21], 0x06, LABEL_0406
	jg [0x21], 0x0D, LABEL_0406
	mov [0x22], [0x21]
	call SAVE_VAR0A_TO_VAR1D
	call DERIVE_VAR30_FROM_HASH_VAR37
	mov [0x22], [0x21]
	call RESTORE_VAR0A_FROM_VAR1D

LABEL_0406:
	add [0x21], 0x0001
	jl [0x21], 0x0F, LABEL_03E5
	mov [0x21], 0x0000

LABEL_0414:
	je [0x21], 0x07, LABEL_0464
	je [0x21], 0x06, LABEL_0464
	jg [0x21], 0x0D, LABEL_0464
	call SUM_HASH_VARS_TO_VAR_37
	mov [0x24], [0x37]
	mov [0x22], [0x24]
	and [0x22], 0x000F
	je [0x22], 0x07, LABEL_0464
	je [0x22], 0x06, LABEL_0464
	jg [0x22], 0x0D, LABEL_0464
	call SAVE_VAR0A_TO_VAR1D
	mov [0x23], [0x1D]
	mov [0x22], [0x21]
	call SAVE_VAR0A_TO_VAR1D
	mov [0x22], [0x24]
	and [0x22], 0x000F
	call RESTORE_VAR0A_FROM_VAR1D
	mov [0x22], [0x21]
	mov [0x1D], [0x23]
	call RESTORE_VAR0A_FROM_VAR1D

LABEL_0464:
	add [0x21], 0x0001
	jl [0x21], 0x10, LABEL_0414
	ret
LABEL_046F:
	db 0x11

DERIVE_VAR30_FROM_HASH_VAR37:
	jne [0x1D], 0x00, SHARED_RET
	mov [0x30], [0x37]
	and [0x30], 0x001D
	add [0x30], 0x0001

ZERO_VAR22:
	mov [0x22], 0x0000

LABEL_0485:
	call SAVE_VAR0A_TO_VAR1D
	jne [0x1D], [0x30], LABEL_049F
	add [0x30], 0x0001
	jl [0x30], 0x1F, ZERO_VAR22
	mov [0x30], 0x0001
	jmp ZERO_VAR22

LABEL_049F:
	add [0x22], 0x0001
	jl [0x22], 0x0F, LABEL_0485
	mov [0x1D], [0x30]
	ret

SAVE_VAR0A_TO_VAR1D:
	jne [0x22], 0x00, LOAD_VAR0B_TO_HASH_VAR1D
	mov [0x1D], [0x0A]
	ret

LOAD_VAR0B_TO_HASH_VAR1D:
	jne [0x22], 0x01, LOAD_VAR0C_TO_HASH_VAR1D
	mov [0x1D], [0x0B]
	ret

LOAD_VAR0C_TO_HASH_VAR1D:
	jne [0x22], 0x02, LOAD_VAR0D_TO_HASH_VAR1D
	mov [0x1D], [0x0C]
	ret

LOAD_VAR0D_TO_HASH_VAR1D:
	jne [0x22], 0x03, LOAD_VAR0E_TO_HASH_VAR1D
	mov [0x1D], [0x0D]
	ret

LOAD_VAR0E_TO_HASH_VAR1D:
	jne [0x22], 0x04, LOAD_VAR0F_TO_HASH_VAR1D
	mov [0x1D], [0x0E]
	ret

LOAD_VAR0F_TO_HASH_VAR1D:
	jne [0x22], 0x05, LOAD_VAR10_TO_HASH_VAR1D
	mov [0x1D], [0x0F]
	ret

LOAD_VAR10_TO_HASH_VAR1D:
	jne [0x22], 0x06, LOAD_VAR11_TO_HASH_VAR1D
	mov [0x1D], [0x10]
	ret

LOAD_VAR11_TO_HASH_VAR1D:
	jne [0x22], 0x07, LOAD_VAR12_TO_HASH_VAR1D
	mov [0x1D], [0x11]
	ret

LOAD_VAR12_TO_HASH_VAR1D:
	jne [0x22], 0x08, LOAD_VAR13_TO_HASH_VAR1D
	mov [0x1D], [0x12]
	ret

LOAD_VAR13_TO_HASH_VAR1D:
	jne [0x22], 0x09, LOAD_VAR14_TO_HASH_VAR1D
	mov [0x1D], [0x13]
	ret

LOAD_VAR14_TO_HASH_VAR1D:
	jne [0x22], 0x0A, LOAD_VAR15_TO_HASH_VAR1D
	mov [0x1D], [0x14]
	ret

LOAD_VAR15_TO_HASH_VAR1D:
	jne [0x22], 0x0B, LOAD_VAR16_TO_HASH_VAR1D
	mov [0x1D], [0x15]
	ret

LOAD_VAR16_TO_HASH_VAR1D:
	jne [0x22], 0x0C, LOAD_VAR17_TO_HASH_VAR1D
	mov [0x1D], [0x16]
	ret

LOAD_VAR17_TO_HASH_VAR1D:
	jne [0x22], 0x0D, LOAD_VAR18_TO_HASH_VAR1D
	mov [0x1D], [0x17]
	ret

LOAD_VAR18_TO_HASH_VAR1D:
	jne [0x22], 0x0E, LOAD_VAR19_TO_HASH_VAR1D
	mov [0x1D], [0x18]
	ret

LOAD_VAR19_TO_HASH_VAR1D:
	jne [0x22], 0x0F, SHARED_RET
	mov [0x1D], [0x19]
	ret
LABEL_054D:
	db 0x11

RESTORE_VAR0A_FROM_VAR1D:
	jne [0x22], 0x00, SAVE_HASH_VAR1D_TO_VAR0B
	mov [0x0A], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR0B:
	jne [0x22], 0x01, SAVE_HASH_VAR1D_TO_VAR0C
	mov [0x0B], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR0C:
	jne [0x22], 0x02, SAVE_HASH_VAR1D_TO_VAR0D
	mov [0x0C], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR0D:
	jne [0x22], 0x03, SAVE_HASH_VAR1D_TO_VAR0E
	mov [0x0D], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR0E:
	jne [0x22], 0x04, SAVE_HASH_VAR1D_TO_VAR0F
	mov [0x0E], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR0F:
	jne [0x22], 0x05, SAVE_HASH_VAR1D_TO_VAR10
	mov [0x0F], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR10:
	jne [0x22], 0x06, SAVE_HASH_VAR1D_TO_VAR11
	mov [0x10], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR11:
	jne [0x22], 0x07, SAVE_HASH_VAR1D_TO_VAR12
	mov [0x11], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR12:
	jne [0x22], 0x08, SAVE_HASH_VAR1D_TO_VAR13
	mov [0x12], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR13:
	jne [0x22], 0x09, SAVE_HASH_VAR1D_TO_VAR14
	mov [0x13], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR14:
	jne [0x22], 0x0A, SAVE_HASH_VAR1D_TO_VAR15
	mov [0x14], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR15:
	jne [0x22], 0x0B, SAVE_HASH_VAR1D_TO_VAR16
	mov [0x15], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR16:
	jne [0x22], 0x0C, SAVE_HASH_VAR1D_TO_VAR17
	mov [0x16], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR17:
	jne [0x22], 0x0D, SAVE_HASH_VAR1D_TO_VAR18
	mov [0x17], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR18:
	jne [0x22], 0x0E, SAVE_HASH_VAR1D_TO_VAR19
	mov [0x18], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR19:
	jne [0x22], 0x0F, SHARED_RET
	mov [0x19], [0x1D]
	ret
LABEL_05EE:
	db 0x11

DERIVE_AND_DRAW_LETTER:
	call DERIVE_VAR07_VAR08_FROM_VAR05
	call BLINK_LETTER_DISPATCHER
	ret

SUM_HASH_VARS_TO_VAR_37:
	add [0x37], [HERO_ACTION]
	add [0x37], [HERO_POS_JUMP_DOWN]
	add [0x37], [HACK_VAR_F7]
	add [0x37], [HERO_ACTION_POS_MASK]
	add [0x37], [0x0A]
	add [0x37], [0x14]
	add [0x37], [0x0B]
	add [0x37], [0x28]
	add [0x37], [0x01]
	add [0x37], [0x04]
	ret

LABEL_0615:
	call SUM_HASH_VARS_TO_VAR_37
	jne [LAST_KEYCHAR], 0x00, LABEL_0ADF
	jne [HERO_ACTION], 0x00, LABEL_0ADF
	mov [0x23], [0x01]
	jne [HERO_POS_UP_DOWN], 0x01, LABEL_063A
	jg [0x01], 0x07, LABEL_064B
	add [0x01], 0x0008
	jmp LABEL_064B

LABEL_063A:
	jne [HERO_POS_UP_DOWN], 0xFFFF, LABEL_064B
	jl [0x01], 0x08, LABEL_064B
	sub [0x01], 0x0008

LABEL_064B:
	jmp LABEL_0673
	jne [HERO_POS_LEFT_RIGHT], 0x01, LABEL_0660
	je [0x01], 0x07, LABEL_068C
	je [0x01], 0x0F, LABEL_068C

LABEL_0660:
	jne [HERO_POS_LEFT_RIGHT], 0xFFFF, LABEL_0673
	je [0x01], 0x00, LABEL_068C
	je [0x01], 0x08, LABEL_068C

LABEL_0673:
	add [0x01], [HERO_POS_LEFT_RIGHT]
	and [0x01], 0x000F
	jne [0x01], 0x06, LABEL_0683
	add [0x01], [HERO_POS_LEFT_RIGHT]

LABEL_0683:
	jne [0x01], 0x0E, LABEL_068C
	add [0x01], [HERO_POS_LEFT_RIGHT]

LABEL_068C:
	mov [0x05], [0x01]
	mov [0x25], [0x07]
	mov [0x26], [0x08]
	call DERIVE_VAR07_VAR08_FROM_VAR05
	mov [0x27], [0x07]
	mov [0x28], [0x08]
	jne [0x25], [0x27], ANIMATE_CURSOR_TRANSITION
	jne [0x26], [0x28], ANIMATE_CURSOR_TRANSITION
	video offset=CINEMATIC_055, x=[0x07], y=[0x08]
	break
	jmp LABEL_0615
LABEL_06B3:
	db 0x11

ANIMATE_CURSOR_TRANSITION:
	mov [0x07], [0x25]
	mov [0x08], [0x26]
	mov [0x24], 0x0003
	jmp COPY_VAR_27_28_TO_07_08

JUNK__06C1:
	jg [0x25], [0x27], LABEL_06D3
	add [0x07], [0x24]
	jl [0x07], [0x27], LABEL_06D3
	mov [0x07], [0x27]

LABEL_06D3:
	jl [0x25], [0x27], LABEL_06E5
	sub [0x07], [0x24]
	jg [0x07], [0x27], LABEL_06E5
	mov [0x07], [0x27]

LABEL_06E5:
	jg [0x26], [0x28], LABEL_06F7
	add [0x08], [0x24]
	jl [0x08], [0x28], LABEL_06F7
	mov [0x08], [0x28]

LABEL_06F7:
	jl [0x26], [0x28], LABEL_0709
	sub [0x08], [0x24]
	jg [0x08], [0x28], LABEL_0709
	mov [0x08], [0x28]

LABEL_0709:
	jne [0x07], [0x27], JUNK__0733
	jne [0x08], [0x28], JUNK__0733
	jmp LABEL_0615

COPY_VAR_27_28_TO_07_08:
	mov [0x07], [0x27]
	mov [0x08], [0x28]

LABEL_071E:
	video offset=CINEMATIC_055, x=[0x07], y=[0x08]
	break
	jne [HERO_POS_UP_DOWN], 0x00, LABEL_071E
	jne [HERO_POS_MASK], 0x00, LABEL_071E
	jmp LABEL_0615

JUNK__0733:
	video offset=CINEMATIC_055, x=[0x07], y=[0x08]
	break
	jmp JUNK__06C1
LABEL_073C:
	db 0x11

LABEL_073D:
	jne [0x1E], 0x15, LABEL_075F
	jne [0x1F], 0x0D, LABEL_075F
	jne [0x20], 0x14, LABEL_075F
	jne [0x21], 0x0D, LABEL_075F
	mov [0x00], 0x000A
	bankSwitch 2;  Arrival at the Lake & Beast Chase
	jmp LABEL_0AA9

LABEL_075F:
	jne [0x1E], 0x11, LABEL_0781
	jne [0x1F], 0x1D, LABEL_0781
	jne [0x20], 0x0D, LABEL_0781
	jne [0x21], 0x0C, LABEL_0781
	mov [0x00], 0x0014
	bankSwitch 3;  Prison Escape
	jmp LABEL_0AA9

LABEL_0781:
	jne [0x1E], 0x0C, LABEL_07A3
	jne [0x1F], 0x15, LABEL_07A3
	jne [0x20], 0x15, LABEL_07A3
	jne [0x21], 0x0D, LABEL_07A3
	mov [0x00], 0x001E
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_07A3:
	jne [0x1E], 0x0F, LABEL_07C5
	jne [0x1F], 0x21, LABEL_07C5
	jne [0x20], 0x15, LABEL_07C5
	jne [0x21], 0x0C, LABEL_07C5
	mov [0x00], 0x0023
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_07C5:
	jne [0x1E], 0x14, LABEL_07E7
	jne [0x1F], 0x1B, LABEL_07E7
	jne [0x20], 0x0F, LABEL_07E7
	jne [0x21], 0x14, LABEL_07E7
	mov [0x00], 0x0025
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_07E7:
	jne [0x1E], 0x21, LABEL_0809
	jne [0x1F], 0x0D, LABEL_0809
	jne [0x20], 0x0D, LABEL_0809
	jne [0x21], 0x13, LABEL_0809
	mov [0x00], 0x0021
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_0809:
	jne [0x1E], 0x15, LABEL_082B
	jne [0x1F], 0x0B, LABEL_082B
	jne [0x20], 0x14, LABEL_082B
	jne [0x21], 0x10, LABEL_082B
	mov [0x00], 0x001F
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_082B:
	jne [0x1E], 0x14, LABEL_084D
	jne [0x1F], 0x15, LABEL_084D
	jne [0x20], 0x0F, LABEL_084D
	jne [0x21], 0x0B, LABEL_084D
	mov [0x00], 0x0027
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_084D:
	jne [0x1E], 0x1D, LABEL_086F
	jne [0x1F], 0x1D, LABEL_086F
	jne [0x20], 0x0C, LABEL_086F
	jne [0x21], 0x1D, LABEL_086F
	mov [0x00], 0x0029
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_086F:
	jne [0x1E], 0x0D, LABEL_0891
	jne [0x1F], 0x0D, LABEL_0891
	jne [0x20], 0x1B, LABEL_0891
	jne [0x21], 0x21, LABEL_0891
	mov [0x00], 0x002A
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_0891:
	jne [0x1E], 0x1D, LABEL_08B3
	jne [0x1F], 0x0B, LABEL_08B3
	jne [0x20], 0x11, LABEL_08B3
	jne [0x21], 0x14, LABEL_08B3
	mov [0x00], 0x002B
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_08B3:
	jne [0x1E], 0x0B, LABEL_08D5
	jne [0x1F], 0x1B, LABEL_08D5
	jne [0x20], 0x1D, LABEL_08D5
	jne [0x21], 0x0D, LABEL_08D5
	mov [0x00], 0x0031
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_08D5:
	jne [0x1E], 0x0C, LABEL_08F7
	jne [0x1F], 0x14, LABEL_08F7
	jne [0x20], 0x13, LABEL_08F7
	jne [0x21], 0x15, LABEL_08F7
	mov [0x00], 0x0032
	bankSwitch 5;  Tank in the Battle Arena
	jmp LABEL_0AA9

LABEL_08F7:
	jne [0x1E], 0x15, LABEL_0919
	jne [0x1F], 0x0F, LABEL_0919
	jne [0x20], 0x0C, LABEL_0919
	jne [0x21], 0x14, LABEL_0919
	mov [0x00], 0x003C
	bankSwitch 6;  Capsule Lands at the Bath
	jmp LABEL_0AA9

LABEL_0919:
	jne [0x1E], 0x0B, LABEL_093B
	jne [0x1F], 0x0F, LABEL_093B
	jne [0x20], 0x15, LABEL_093B
	jne [0x21], 0x21, LABEL_093B
	mov [0x00], 0x002C
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_093B:
	jne [0x1E], 0x21, LABEL_095D
	jne [0x1F], 0x13, LABEL_095D
	jne [0x20], 0x1B, LABEL_095D
	jne [0x21], 0x1D, LABEL_095D
	mov [0x00], 0x002D
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_095D:
	jne [0x1E], 0x11, LABEL_097F
	jne [0x1F], 0x1B, LABEL_097F
	jne [0x20], 0x1D, LABEL_097F
	jne [0x21], 0x0B, LABEL_097F
	mov [0x00], 0x002E
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_097F:
	jne [0x1E], 0x11, LABEL_09A1
	jne [0x1F], 0x0B, LABEL_09A1
	jne [0x20], 0x11, LABEL_09A1
	jne [0x21], 0x14, LABEL_09A1
	mov [0x00], 0x002F
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_09A1:
	jne [0x1E], 0x13, LABEL_09C3
	jne [0x1F], 0x0C, LABEL_09C3
	jne [0x20], 0x10, LABEL_09C3
	jne [0x21], 0x0B, LABEL_09C3
	mov [0x00], 0x0030
	bankSwitch 4;  Gas tunnels, Caves and Pool
	jmp LABEL_0AA9

LABEL_09C3:
	jne [0x1E], 0x11, LABEL_09E5
	jne [0x1F], 0x11, LABEL_09E5
	jne [0x20], 0x0F, LABEL_09E5
	jne [0x21], 0x15, LABEL_09E5
	mov [0x00], 0x003E
	bankSwitch 6;  Capsule Lands at the Bath
	jmp LABEL_0AA9

LABEL_09E5:
	jne [0x1E], 0x1D, LABEL_0A07
	jne [0x1F], 0x0F, LABEL_0A07
	jne [0x20], 0x0B, LABEL_0A07
	jne [0x21], 0x0B, LABEL_0A07
	mov [0x00], 0x0040
	bankSwitch 6;  Capsule Lands at the Bath
	jmp LABEL_0AA9

LABEL_0A07:
	jne [0x1E], 0x1D, LABEL_0A29
	jne [0x1F], 0x21, LABEL_0A29
	jne [0x20], 0x11, LABEL_0A29
	jne [0x21], 0x0F, LABEL_0A29
	mov [0x00], 0x0042
	bankSwitch 6;  Capsule Lands at the Bath
	jmp LABEL_0AA9

LABEL_0A29:
	jne [0x1E], 0x13, LABEL_0A4B
	jne [0x1F], 0x11, LABEL_0A4B
	jne [0x20], 0x13, LABEL_0A4B
	jne [0x21], 0x15, LABEL_0A4B
	mov [0x00], 0x0044
	bankSwitch 6;  Capsule Lands at the Bath
	jmp LABEL_0AA9

LABEL_0A4B:
	jne [0x1E], 0x14, LABEL_0A6D
	jne [0x1F], 0x1B, LABEL_0A6D
	jne [0x20], 0x1D, LABEL_0A6D
	jne [0x21], 0x0D, LABEL_0A6D
	mov [0x00], 0x0046
	bankSwitch 7;  Game Ending Sequence
	jmp LABEL_0AA9

LABEL_0A6D:
	jne [0x1E], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x1F], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x20], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x21], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	mov [0x00], 0x0000
	bankSwitch 1;  Intro Sequence
	jmp LABEL_0AA9

SET_VAR_E6_F_PAUSE_4:
	mov [0xE6], 0x000F
	mov [PAUSE_SLICES], 0x0004

LABEL_0A9B:
	text id=0x013F, x=7, y=100, color=0x05 ; "   INVALID PASSWORD !"
	break
	djnz [0xE6], LABEL_0A9B
	jmp LABEL_0000

LABEL_0AA9:
	setPalette 0x00
	jmp LABEL_0000
LABEL_0AAF:
	db 0x11

INTERPRET_KEY_TO_LETTER:
	jne [LAST_KEYCHAR], 0x0D, HANDLE_BACKSPACE_KEY
	mov [0x06], 0x0063
	ret

HANDLE_BACKSPACE_KEY:
	jne [LAST_KEYCHAR], 0x08, MAP_KEY_A_TO_Z_TO_INDEX
	mov [0x06], 0x0062
	ret

MAP_KEY_A_TO_Z_TO_INDEX:
	jl [LAST_KEYCHAR], 0x41, CLEAR_LAST_KEYCHAR
	jg [LAST_KEYCHAR], 0x5A, CLEAR_LAST_KEYCHAR
	mov [0x06], [LAST_KEYCHAR]
	sub [0x06], 0x0037
	ret

CLEAR_LAST_KEYCHAR:
	mov [LAST_KEYCHAR], 0x0000
	ret

LABEL_0ADF:
	mov [0x05], [0x01]
	je [LAST_KEYCHAR], 0x00, DISPATCH_AND_CALL_INDEX_VAR06
	call INTERPRET_KEY_TO_LETTER
	je [LAST_KEYCHAR], 0x00, LABEL_0B53
	jmp LABEL_0AF7

DISPATCH_AND_CALL_INDEX_VAR06:
	call INDEX_VAR06_BY_VAR05

LABEL_0AF7:
	mov [0x22], [0x02]
	je [0x06], 0x63, LABEL_073D
	jne [0x06], 0x62, LABEL_0B1B
	mov [0x06], 0xFFFF
	sub [0x22], 0x0001
	jg [0x22], 0x00, LABEL_0B29
	mov [0x22], 0x0000
	jmp LABEL_0B29

LABEL_0B1B:
	je [0x02], 0x04, LABEL_0B53
	add [0x22], 0x0001
	add [0x02], 0x0001

LABEL_0B29:
	jne [0x02], 0x01, LABEL_0B32
	mov [0x1E], [0x06]

LABEL_0B32:
	jne [0x02], 0x02, SAVE_PASSCODE_LETTER_3
	mov [0x1F], [0x06]

SAVE_PASSCODE_LETTER_3:
	jne [0x02], 0x03, SAVE_PASSCODE_LETTER_4
	mov [0x20], [0x06]

SAVE_PASSCODE_LETTER_4:
	jne [0x02], 0x04, SETUP_VAR02_FROM_VAR22
	mov [0x21], [0x06]

SETUP_VAR02_FROM_VAR22:
	call DRAW_CIN_056_AT_BC_54
	mov [0x02], [0x22]

LABEL_0B53:
	mov [0x05], [0x01]
	call DERIVE_VAR07_VAR08_FROM_VAR05
	video offset=CINEMATIC_055, x=[0x07], y=[0x08]
	break
	jne [LAST_KEYCHAR], 0x00, LABEL_0B53
	jne [HERO_ACTION], 0x00, LABEL_0B53
	jmp LABEL_0615
LABEL_0B6E:
	db 0x11

DRAW_CIN_056_AT_BC_54:
	mov [0x07], 0x00BC
	mov [0x08], 0x0054
	selectVideoPage 0x00
	video offset=CINEMATIC_056, x=160, y=100
	text id=0x013C, x=2, y=80, color=0x06 ; "        ACCESS CODE:"
	mov [0x06], [0x1E]
	call BLINK_LETTER_DISPATCHER
	add [0x07], 0x0008
	mov [0x06], [0x1F]
	call BLINK_LETTER_DISPATCHER
	add [0x07], 0x0008
	mov [0x06], [0x20]
	call BLINK_LETTER_DISPATCHER
	add [0x07], 0x0008
	mov [0x06], [0x21]
	call BLINK_LETTER_DISPATCHER
	selectVideoPage 0xFF
	ret

DERIVE_VAR07_VAR08_FROM_VAR05:
	mov [0x07], [0x05]
	mov [0x08], [0x05]
	and [0x07], 0x0007
	and [0x08], 0x0008
	jne [0x08], 0x00, INIT_VAR08_TO_150
	mov [0x08], 0x0086
	jmp SCALE_VAR07_TIMES_9_PLUS_4A

INIT_VAR08_TO_150:
	mov [0x08], 0x0096

SCALE_VAR07_TIMES_9_PLUS_4A:
	shl [0x07], 0x0003
	mov [0xF8], [0x07]
	add [0x07], [0xF8]
	add [0x07], 0x004A
	je [0xDB], 0x00, SHARED_RET
	add [0x07], 0x0004
	ret

DRAW_LETTER_2_DISPATCH_BY_X:
	je [0x07], 0xC4, DRAW_LETTER_2_AT_X24
	je [0x07], 0xCC, DRAW_LETTER_2_AT_X25
	je [0x07], 0xD4, DRAW_LETTER_2_AT_X26
	jne [0x07], 0xBC, SHARED_RET
	jne [0x06], 0x0B, DRAW_LETTER_3_AT_X23
	text id=0x012E, x=23, y=80, color=0x04 ; "2"
	ret

DRAW_LETTER_3_AT_X23:
	jne [0x06], 0x0C, DRAW_LETTER_4_AT_X23
	text id=0x012F, x=23, y=80, color=0x04 ; "3"
	ret

DRAW_LETTER_4_AT_X23:
	jne [0x06], 0x0D, DRAW_LETTER_5_AT_X23
	text id=0x0130, x=23, y=80, color=0x04 ; "4"
	ret

DRAW_LETTER_5_AT_X23:
	jne [0x06], 0x0F, DRAW_LETTER_6_AT_X23
	text id=0x0131, x=23, y=80, color=0x04 ; "5"
	ret

DRAW_LETTER_6_AT_X23:
	jne [0x06], 0x10, DRAW_LETTER_7_AT_X23
	text id=0x0132, x=23, y=80, color=0x04 ; "6"
	ret

DRAW_LETTER_7_AT_X23:
	jne [0x06], 0x11, DRAW_LETTER_8_AT_X23
	text id=0x0133, x=23, y=80, color=0x04 ; "7"
	ret

DRAW_LETTER_8_AT_X23:
	jne [0x06], 0x13, DRAW_LETTER_9_AT_X23
	text id=0x0134, x=23, y=80, color=0x04 ; "8"
	ret

DRAW_LETTER_9_AT_X23:
	jne [0x06], 0x14, DRAW_LETTER_A_AT_X23
	text id=0x0135, x=23, y=80, color=0x04 ; "9"
	ret

DRAW_LETTER_A_AT_X23:
	jne [0x06], 0x15, DRAW_LETTER_B_AT_X23
	text id=0x0136, x=23, y=80, color=0x04 ; "A"
	ret

DRAW_LETTER_B_AT_X23:
	jne [0x06], 0x1B, DRAW_LETTER_C_AT_X23
	text id=0x0137, x=23, y=80, color=0x04 ; "B"
	ret

DRAW_LETTER_C_AT_X23:
	jne [0x06], 0x21, DRAW_LETTER_D_AT_X23
	text id=0x0138, x=23, y=80, color=0x04 ; "C"
	ret

DRAW_LETTER_D_AT_X23:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=23, y=80, color=0x04 ; "D"
	ret

DRAW_LETTER_2_AT_X24:
	jne [0x06], 0x0B, DRAW_LETTER_3_AT_X24
	text id=0x012E, x=24, y=80, color=0x04 ; "2"
	ret

DRAW_LETTER_3_AT_X24:
	jne [0x06], 0x0C, DRAW_LETTER_4_AT_X24
	text id=0x012F, x=24, y=80, color=0x04 ; "3"
	ret

DRAW_LETTER_4_AT_X24:
	jne [0x06], 0x0D, DRAW_LETTER_5_AT_X24
	text id=0x0130, x=24, y=80, color=0x04 ; "4"
	ret

DRAW_LETTER_5_AT_X24:
	jne [0x06], 0x0F, DRAW_LETTER_6_AT_X24
	text id=0x0131, x=24, y=80, color=0x04 ; "5"
	ret

DRAW_LETTER_6_AT_X24:
	jne [0x06], 0x10, DRAW_LETTER_7_AT_X24
	text id=0x0132, x=24, y=80, color=0x04 ; "6"
	ret

DRAW_LETTER_7_AT_X24:
	jne [0x06], 0x11, DRAW_LETTER_8_AT_X24
	text id=0x0133, x=24, y=80, color=0x04 ; "7"
	ret

DRAW_LETTER_8_AT_X24:
	jne [0x06], 0x13, DRAW_LETTER_9_AT_X24
	text id=0x0134, x=24, y=80, color=0x04 ; "8"
	ret

DRAW_LETTER_9_AT_X24:
	jne [0x06], 0x14, DRAW_LETTER_A_AT_X24
	text id=0x0135, x=24, y=80, color=0x04 ; "9"
	ret

DRAW_LETTER_A_AT_X24:
	jne [0x06], 0x15, DRAW_LETTER_B_AT_X24
	text id=0x0136, x=24, y=80, color=0x04 ; "A"
	ret

DRAW_LETTER_B_AT_X24:
	jne [0x06], 0x1B, DRAW_LETTER_C_AT_X24
	text id=0x0137, x=24, y=80, color=0x04 ; "B"
	ret

DRAW_LETTER_C_AT_X24:
	jne [0x06], 0x21, DRAW_LETTER_D_AT_X24
	text id=0x0138, x=24, y=80, color=0x04 ; "C"
	ret

DRAW_LETTER_D_AT_X24:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=24, y=80, color=0x04 ; "D"
	ret

DRAW_LETTER_2_AT_X25:
	jne [0x06], 0x0B, DRAW_LETTER_3_AT_X25
	text id=0x012E, x=25, y=80, color=0x04 ; "2"
	ret

DRAW_LETTER_3_AT_X25:
	jne [0x06], 0x0C, DRAW_LETTER_4_AT_X25
	text id=0x012F, x=25, y=80, color=0x04 ; "3"
	ret

DRAW_LETTER_4_AT_X25:
	jne [0x06], 0x0D, DRAW_LETTER_5_AT_X25
	text id=0x0130, x=25, y=80, color=0x04 ; "4"
	ret

DRAW_LETTER_5_AT_X25:
	jne [0x06], 0x0F, DRAW_LETTER_6_AT_X25
	text id=0x0131, x=25, y=80, color=0x04 ; "5"
	ret

DRAW_LETTER_6_AT_X25:
	jne [0x06], 0x10, DRAW_LETTER_7_AT_X25
	text id=0x0132, x=25, y=80, color=0x04 ; "6"
	ret

DRAW_LETTER_7_AT_X25:
	jne [0x06], 0x11, DRAW_LETTER_8_AT_X25
	text id=0x0133, x=25, y=80, color=0x04 ; "7"
	ret

DRAW_LETTER_8_AT_X25:
	jne [0x06], 0x13, DRAW_LETTER_9_AT_X25
	text id=0x0134, x=25, y=80, color=0x04 ; "8"
	ret

DRAW_LETTER_9_AT_X25:
	jne [0x06], 0x14, DRAW_LETTER_A_AT_X25
	text id=0x0135, x=25, y=80, color=0x04 ; "9"
	ret

DRAW_LETTER_A_AT_X25:
	jne [0x06], 0x15, DRAW_LETTER_B_AT_X25
	text id=0x0136, x=25, y=80, color=0x04 ; "A"
	ret

DRAW_LETTER_B_AT_X25:
	jne [0x06], 0x1B, DRAW_LETTER_C_AT_X25
	text id=0x0137, x=25, y=80, color=0x04 ; "B"
	ret

DRAW_LETTER_C_AT_X25:
	jne [0x06], 0x21, DRAW_LETTER_D_AT_X25
	text id=0x0138, x=25, y=80, color=0x04 ; "C"
	ret

DRAW_LETTER_D_AT_X25:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=25, y=80, color=0x04 ; "D"
	ret

DRAW_LETTER_2_AT_X26:
	jne [0x06], 0x0B, DRAW_LETTER_3_AT_X26
	text id=0x012E, x=26, y=80, color=0x04 ; "2"
	ret

DRAW_LETTER_3_AT_X26:
	jne [0x06], 0x0C, DRAW_LETTER_4_AT_X26
	text id=0x012F, x=26, y=80, color=0x04 ; "3"
	ret

DRAW_LETTER_4_AT_X26:
	jne [0x06], 0x0D, DRAW_LETTER_5_AT_X26
	text id=0x0130, x=26, y=80, color=0x04 ; "4"
	ret

DRAW_LETTER_5_AT_X26:
	jne [0x06], 0x0F, DRAW_LETTER_6_AT_X26
	text id=0x0131, x=26, y=80, color=0x04 ; "5"
	ret

DRAW_LETTER_6_AT_X26:
	jne [0x06], 0x10, DRAW_LETTER_7_AT_X26
	text id=0x0132, x=26, y=80, color=0x04 ; "6"
	ret

DRAW_LETTER_7_AT_X26:
	jne [0x06], 0x11, DRAW_LETTER_8_AT_X26
	text id=0x0133, x=26, y=80, color=0x04 ; "7"
	ret

DRAW_LETTER_8_AT_X26:
	jne [0x06], 0x13, DRAW_LETTER_9_AT_X26
	text id=0x0134, x=26, y=80, color=0x04 ; "8"
	ret

DRAW_LETTER_9_AT_X26:
	jne [0x06], 0x14, DRAW_LETTER_A_AT_X26
	text id=0x0135, x=26, y=80, color=0x04 ; "9"
	ret

DRAW_LETTER_A_AT_X26:
	jne [0x06], 0x15, DRAW_LETTER_B_AT_X26
	text id=0x0136, x=26, y=80, color=0x04 ; "A"
	ret

DRAW_LETTER_B_AT_X26:
	jne [0x06], 0x1B, DRAW_LETTER_C_AT_X26
	text id=0x0137, x=26, y=80, color=0x04 ; "B"
	ret

DRAW_LETTER_C_AT_X26:
	jne [0x06], 0x21, DRAW_LETTER_D_AT_X26
	text id=0x0138, x=26, y=80, color=0x04 ; "C"
	ret

DRAW_LETTER_D_AT_X26:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=26, y=80, color=0x04 ; "D"
	ret

BLINK_LETTER_DISPATCHER:
	je [0x06], 0x62, DRAW_CIN_053_IF_VAR06_EQ_2
	je [0x06], 0x63, DRAW_CIN_053_IF_VAR06_EQ_2
	jne [0xDB], 0x00, DRAW_LETTER_2_DISPATCH_BY_X
	jne [0x06], 0x01, DRAW_CIN_053_IF_VAR06_EQ_2
	video offset=CINEMATIC_054, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_CIN_053_IF_VAR06_EQ_2:
	jne [0x06], 0x02, DRAW_GLYPH_KEY03_CIN_052
	video offset=CINEMATIC_053, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY03_CIN_052:
	jne [0x06], 0x03, DRAW_GLYPH_KEY04_CIN_051
	video offset=CINEMATIC_052, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY04_CIN_051:
	jne [0x06], 0x04, DRAW_GLYPH_KEY05_CIN_050
	video offset=CINEMATIC_051, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY05_CIN_050:
	jne [0x06], 0x05, DRAW_GLYPH_KEY06_CIN_049
	video offset=CINEMATIC_050, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY06_CIN_049:
	jne [0x06], 0x06, DRAW_GLYPH_KEY07_CIN_048
	video offset=CINEMATIC_049, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY07_CIN_048:
	jne [0x06], 0x07, DRAW_GLYPH_KEY08_CIN_047
	video offset=CINEMATIC_048, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY08_CIN_047:
	jne [0x06], 0x08, DRAW_GLYPH_KEY09_CIN_046
	video offset=CINEMATIC_047, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY09_CIN_046:
	jne [0x06], 0x09, DRAW_LETTER_A_CIN_045
	video offset=CINEMATIC_046, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_A_CIN_045:
	jne [0x06], 0x0A, DRAW_LETTER_B_CIN_044
	video offset=CINEMATIC_045, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_B_CIN_044:
	jne [0x06], 0x0B, DRAW_LETTER_C_CIN_043
	video offset=CINEMATIC_044, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_C_CIN_043:
	jne [0x06], 0x0C, DRAW_LETTER_D_CIN_042
	video offset=CINEMATIC_043, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_D_CIN_042:
	jne [0x06], 0x0D, DRAW_LETTER_E_CIN_041
	video offset=CINEMATIC_042, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_E_CIN_041:
	jne [0x06], 0x0E, DRAW_LETTER_F_CIN_040
	video offset=CINEMATIC_041, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_F_CIN_040:
	jne [0x06], 0x0F, DRAW_LETTER_G_CIN_039
	video offset=CINEMATIC_040, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_G_CIN_039:
	jne [0x06], 0x10, DRAW_LETTER_VIA_CIN_DISPATCH
	video offset=CINEMATIC_039, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_VIA_CIN_DISPATCH:
	jne [0x06], 0x62, DRAW_CIN_000_LETTER_BLANK
	video offset=CINEMATIC_038, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_CIN_000_LETTER_BLANK:
	jne [0x06], 0x63, DRAW_GLYPH_KEY00_CIN_036
	video offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY00_CIN_036:
	jne [0x06], 0x00, DRAW_LETTER_H_CIN_035
	video offset=CINEMATIC_036, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_H_CIN_035:
	jne [0x06], 0x11, DRAW_LETTER_I_CIN_034
	video offset=CINEMATIC_035, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_I_CIN_034:
	jne [0x06], 0x12, DRAW_LETTER_J_CIN_033
	video offset=CINEMATIC_034, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_J_CIN_033:
	jne [0x06], 0x13, DRAW_LETTER_K_CIN_032
	video offset=CINEMATIC_033, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_K_CIN_032:
	jne [0x06], 0x14, DRAW_LETTER_L_CIN_031
	video offset=CINEMATIC_032, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_L_CIN_031:
	jne [0x06], 0x15, DRAW_LETTER_M_CIN_030
	video offset=CINEMATIC_031, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_M_CIN_030:
	jne [0x06], 0x16, DRAW_LETTER_N_CIN_029
	video offset=CINEMATIC_030, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_N_CIN_029:
	jne [0x06], 0x17, DRAW_LETTER_O_CIN_028
	video offset=CINEMATIC_029, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_O_CIN_028:
	jne [0x06], 0x18, DRAW_LETTER_P_CIN_027
	video offset=CINEMATIC_028, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_P_CIN_027:
	jne [0x06], 0x19, DRAW_LETTER_Q_CIN_026
	video offset=CINEMATIC_027, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_Q_CIN_026:
	jne [0x06], 0x1A, DRAW_LETTER_R_CIN_025
	video offset=CINEMATIC_026, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_R_CIN_025:
	jne [0x06], 0x1B, DRAW_LETTER_S_CIN_024
	video offset=CINEMATIC_025, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_S_CIN_024:
	jne [0x06], 0x1C, DRAW_LETTER_T_CIN_023
	video offset=CINEMATIC_024, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_T_CIN_023:
	jne [0x06], 0x1D, DRAW_LETTER_U_CIN_022
	video offset=CINEMATIC_023, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_U_CIN_022:
	jne [0x06], 0x1E, DRAW_LETTER_V_CIN_021
	video offset=CINEMATIC_022, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_V_CIN_021:
	jne [0x06], 0x1F, DRAW_LETTER_W_CIN_020
	video offset=CINEMATIC_021, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_W_CIN_020:
	jne [0x06], 0x20, DRAW_LETTER_X_CIN_019
	video offset=CINEMATIC_020, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_X_CIN_019:
	jne [0x06], 0x21, DRAW_LETTER_Y_CIN_018
	video offset=CINEMATIC_019, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_Y_CIN_018:
	jne [0x06], 0x22, DRAW_LETTER_Z_CIN_017
	video offset=CINEMATIC_018, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_LETTER_Z_CIN_017:
	jne [0x06], 0x23, DRAW_GLYPH_KEY24_CIN_017
	video offset=CINEMATIC_017, x=[0x07], y=[0x08], zoom=[0x04]
	ret

DRAW_GLYPH_KEY24_CIN_017:
	jne [0x06], 0x24, SHARED_RET
	video offset=CINEMATIC_017, x=[0x07], y=[0x08], zoom=[0x04]
	ret

SHARED_RET:
	ret
	killChannel
	video offset=CINEMATIC_057, x=160, y=100

LABEL_107D:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	break
	jmp LABEL_107D

JUNK__1088:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	break
	jmp JUNK__1088

LABEL_1090:
	fill page=0x01, color=0x00
	fill page=0x02, color=0x00
	selectVideoPage 0x01
	blitFramebuffer 0x01
	blitFramebuffer 0xFF
	blitFramebuffer 0x02
	ret
LABEL_109F:
	db 0x11, 0x11, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
	FILL(61273, 0xFF)
