LABEL_956C:
	video type=0, offset=COMMON_VIDEO_081, x=[0x01], y=[0x02], zoom=0x40
	play id=0x0060, freq=0x0F, vol=0x2A, channel=0x01
	jne [0x0A], 0x00, DRAW_CV_295
	video type=0, offset=COMMON_VIDEO_082, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_9583:
	video type=0, offset=COMMON_VIDEO_083, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_296
	video type=0, offset=COMMON_VIDEO_084, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_9594:
	video type=0, offset=COMMON_VIDEO_116, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_299
	video type=0, offset=COMMON_VIDEO_117, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_95A5:
	video type=0, offset=COMMON_VIDEO_118, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_300
	video type=0, offset=COMMON_VIDEO_119, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_95B6:
	video type=0, offset=COMMON_VIDEO_120, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_300
	video type=0, offset=COMMON_VIDEO_121, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_95C7:
	video type=0, offset=COMMON_VIDEO_086, x=[0x01], y=[0x02], zoom=0x40
	play id=0x0060, freq=0x0A, vol=0x2A, channel=0x01
	jne [0x0A], 0x00, DRAW_CV_295
	video type=0, offset=COMMON_VIDEO_087, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_95DE:
	video type=0, offset=COMMON_VIDEO_088, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_295
	video type=0, offset=COMMON_VIDEO_089, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_95EF:
	video type=0, offset=COMMON_VIDEO_090, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_296
	video type=0, offset=COMMON_VIDEO_091, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_9600:
	video type=0, offset=COMMON_VIDEO_092, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_297
	video type=0, offset=COMMON_VIDEO_093, x=[0x01], y=[0x02], zoom=0x40
	ret

LABEL_9611:
	video type=0, offset=COMMON_VIDEO_094, x=[0x01], y=[0x02], zoom=0x40
	jne [0x0A], 0x00, DRAW_CV_297
	video type=0, offset=COMMON_VIDEO_095, x=[0x01], y=[0x02], zoom=0x40
	ret
