LABEL_1B75:
	mov [0x06], 0x0002
	mov [0x04], 0x0002
	break
	break
	mov [0x06], 0x0003
	break
	mov [0x04], 0x0001
	break
	mov [0x06], 0x0004
	break
	break
	mov [0x06], 0x0001
	break
	mov [0x04], 0x0002
	break
	break
	mov [0x06], 0x0002
	mov [0x04], 0x0003
	break
	break
	mov [0x06], 0x0004
	mov [0x04], 0x0004
	sub [0x07], 0x0001
	break
	sub [0x07], 0x0004
	break
	mov [0x06], 0x0001
	sub [0x07], 0x0001
	sub [0x05], 0x0002
	break
	break
	mov [0x04], 0x0001
	sub [0x05], 0x0002
	break
	mov [0x06], 0x0002
	sub [0x05], 0x0002
	break
	jmp LABEL_1ADA
LABEL_1BD9:
	db 0x11

LABEL_1BDA:
	video type=1, offset=CINEMATIC_221, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_221, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_221, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_221, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_224, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_224, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_224, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_224, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_223, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	video type=1, offset=CINEMATIC_222, x=[0x0a], y=100, zoom=0x40
	break
	jmp LABEL_1BDA
