DRAW_CIN_073_IF_VAR06_EQ_1:
	jne [0x06], 0x01, LABEL_0E88
	video offset=CINEMATIC_073, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0E88:
	jne [0x06], 0x02, LABEL_0E95
	video offset=CINEMATIC_072, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0E95:
	jne [0x06], 0x03, LABEL_0EA2
	video offset=CINEMATIC_071, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EA2:
	jne [0x06], 0x04, LABEL_0EAF
	video offset=CINEMATIC_070, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EAF:
	jne [0x06], 0x05, LABEL_0EBC
	video offset=CINEMATIC_069, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EBC:
	jne [0x06], 0x06, LABEL_0EC9
	video offset=CINEMATIC_068, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EC9:
	jne [0x06], 0x07, LABEL_0ED6
	video offset=CINEMATIC_067, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0ED6:
	jne [0x06], 0x08, LABEL_0EE3
	video offset=CINEMATIC_066, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EE3:
	jne [0x06], 0x09, LABEL_0EF0
	video offset=CINEMATIC_065, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EF0:
	jne [0x06], 0x0A, LABEL_0EFD
	video offset=CINEMATIC_064, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0EFD:
	jne [0x06], 0x0B, LABEL_0F0A
	video offset=CINEMATIC_063, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F0A:
	jne [0x06], 0x0C, LABEL_0F17
	video offset=CINEMATIC_062, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F17:
	jne [0x06], 0x0D, LABEL_0F24
	video offset=CINEMATIC_061, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F24:
	jne [0x06], 0x0E, LABEL_0F31
	video offset=CINEMATIC_060, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F31:
	jne [0x06], 0x0F, LABEL_0F3E
	video offset=CINEMATIC_059, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F3E:
	jne [0x06], 0x10, LABEL_0F4B
	video offset=CINEMATIC_058, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F4B:
	jne [0x06], 0x62, LABEL_0F58
	video offset=CINEMATIC_057, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F58:
	jne [0x06], 0x63, LABEL_0F65
	video offset=CINEMATIC_056, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F65:
	jne [0x06], 0x11, LABEL_0F72
	video offset=CINEMATIC_055, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F72:
	jne [0x06], 0x12, LABEL_0F7F
	video offset=CINEMATIC_054, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F7F:
	jne [0x06], 0x13, LABEL_0F8C
	video offset=CINEMATIC_053, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F8C:
	jne [0x06], 0x14, LABEL_0F99
	video offset=CINEMATIC_052, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0F99:
	jne [0x06], 0x15, LABEL_0FA6
	video offset=CINEMATIC_051, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FA6:
	jne [0x06], 0x16, LABEL_0FB3
	video offset=CINEMATIC_050, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FB3:
	jne [0x06], 0x17, LABEL_0FC0
	video offset=CINEMATIC_049, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FC0:
	jne [0x06], 0x18, LABEL_0FCD
	video offset=CINEMATIC_048, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FCD:
	jne [0x06], 0x19, LABEL_0FDA
	video offset=CINEMATIC_047, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FDA:
	jne [0x06], 0x1A, LABEL_0FE7
	video offset=CINEMATIC_046, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FE7:
	jne [0x06], 0x1B, LABEL_0FF4
	video offset=CINEMATIC_045, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_0FF4:
	jne [0x06], 0x1C, LABEL_1001
	video offset=CINEMATIC_044, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1001:
	jne [0x06], 0x1D, LABEL_100E
	video offset=CINEMATIC_043, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_100E:
	jne [0x06], 0x1E, LABEL_101B
	video offset=CINEMATIC_042, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_101B:
	jne [0x06], 0x1F, LABEL_1028
	video offset=CINEMATIC_041, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1028:
	jne [0x06], 0x20, LABEL_1035
	video offset=CINEMATIC_040, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1035:
	jne [0x06], 0x21, LABEL_1042
	video offset=CINEMATIC_039, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1042:
	jne [0x06], 0x22, LABEL_104F
	video offset=CINEMATIC_038, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_104F:
	jne [0x06], 0x23, LABEL_105C
	video offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_105C:
	jne [0x06], 0x24, LABEL_1069
	video offset=CINEMATIC_036, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1069:
	jne [0x06], 0x25, LABEL_1076
	video offset=CINEMATIC_035, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1076:
	jne [0x06], 0x26, LABEL_1083
	video offset=CINEMATIC_034, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1083:
	jne [0x06], 0x27, LABEL_1090
	video offset=CINEMATIC_033, x=[0x07], y=[0x08], zoom=[0x04]
	ret

LABEL_1090:
	jne [0x06], 0x28, SHARED_RET
	video offset=CINEMATIC_032, x=[0x07], y=[0x08], zoom=[0x04]
	ret

SHARED_RET:
	ret
	killChannel
	video offset=CINEMATIC_079, x=160, y=100

BLITTER_LOOP_WITH_VAR1B_2B:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	mov [0x1B], 0x002B
	break
	jmp BLITTER_LOOP_WITH_VAR1B_2B

LABEL_10B2:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	mov [0x1B], 0x002B
	break
	jmp LABEL_10B2

LABEL_10C1:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	mov [0x1B], 0x0015
	break
	jmp LABEL_10C1
