; STAGE ENDING: final cinematic + escape on the pteranodon-creature.
;
; Gameplay role: closing cinematic after all gameplay stages
; complete. The alien friend rescues Lester one last time and they
; ride off together on a giant flying creature.
;
; This file: cartridge_1992 (Heineman SNES + Genesis port)
;
;
; Structure: only 28 folded bodies. Mostly DRAW_CIN_<N>_TO_<M>
; sequences and PALETTE_FADE animations. Like CAVES, has empty
; post-fold chunks blocking the cleanup pass.
;
; Generated by AnotherWorld_VMTools
;@include "../_common_vars.inc"
CINEMATIC_000		EQU 0x06E8
CINEMATIC_001		EQU 0x02A8
CINEMATIC_002		EQU 0x0544
CINEMATIC_003		EQU 0x0230
CINEMATIC_004		EQU 0x234C
CINEMATIC_005		EQU 0x1A2C
CINEMATIC_006		EQU 0x1CA0
CINEMATIC_007		EQU 0x27F8
CINEMATIC_008		EQU 0x0704
CINEMATIC_009		EQU 0x0794
CINEMATIC_010		EQU 0x3914
CINEMATIC_011		EQU 0x0C16
CINEMATIC_012		EQU 0x0BAC
CINEMATIC_013		EQU 0x08FC
CINEMATIC_014		EQU 0x0A64
CINEMATIC_015		EQU 0x0A10
CINEMATIC_016		EQU 0x0914
CINEMATIC_017		EQU 0x0968
CINEMATIC_018		EQU 0x09BC
CINEMATIC_019		EQU 0x0C7C
CINEMATIC_020		EQU 0x0CD0
CINEMATIC_021		EQU 0x0DE4
CINEMATIC_022		EQU 0x0D24
CINEMATIC_023		EQU 0x0D86
CINEMATIC_024		EQU 0x0B40
CINEMATIC_025		EQU 0x0AB8
CINEMATIC_026		EQU 0x0F04
CINEMATIC_027		EQU 0x0FC4
CINEMATIC_028		EQU 0x108C
CINEMATIC_029		EQU 0x1144
CINEMATIC_030		EQU 0x11FC
CINEMATIC_031		EQU 0x12B4
CINEMATIC_032		EQU 0x13C8
CINEMATIC_033		EQU 0x1480
CINEMATIC_034		EQU 0x1548
CINEMATIC_035		EQU 0x1610
CINEMATIC_036		EQU 0x16D4
CINEMATIC_037		EQU 0x183C
CINEMATIC_038		EQU 0x1BD4
CINEMATIC_039		EQU 0x1D86
CINEMATIC_040		EQU 0x1AFA
CINEMATIC_041		EQU 0x1E44
CINEMATIC_042		EQU 0x1E60
CINEMATIC_043		EQU 0x1EA0
CINEMATIC_044		EQU 0x1EE0
CINEMATIC_045		EQU 0x1F30
CINEMATIC_046		EQU 0x1F98
CINEMATIC_047		EQU 0x2004
CINEMATIC_048		EQU 0x2044
CINEMATIC_049		EQU 0x2084
CINEMATIC_050		EQU 0x20D4
CINEMATIC_051		EQU 0x213C
CINEMATIC_052		EQU 0x33DC
CINEMATIC_053		EQU 0x3380
CINEMATIC_054		EQU 0x32C8
CINEMATIC_055		EQU 0x3208
CINEMATIC_056		EQU 0x3268
CINEMATIC_057		EQU 0x3324
CINEMATIC_058		EQU 0x3F5C
CINEMATIC_059		EQU 0x40D2
CINEMATIC_060		EQU 0x40EE
CINEMATIC_061		EQU 0x410A
CINEMATIC_062		EQU 0x4126
CINEMATIC_063		EQU 0x4142
CINEMATIC_064		EQU 0x415E
CINEMATIC_065		EQU 0x417A
CINEMATIC_066		EQU 0x2A74
CINEMATIC_067		EQU 0x3E58
CINEMATIC_068		EQU 0x3C50
CINEMATIC_069		EQU 0x3D54
CINEMATIC_070		EQU 0x40C6
CINEMATIC_071		EQU 0x3B64
CINEMATIC_072		EQU 0x3B24
CINEMATIC_073		EQU 0x3AE4
CINEMATIC_074		EQU 0x3AD0
CINEMATIC_075		EQU 0x2F48
CINEMATIC_076		EQU 0x2F94
CINEMATIC_077		EQU 0x2FE0
CINEMATIC_078		EQU 0x3028
CINEMATIC_079		EQU 0x307C
CINEMATIC_080		EQU 0x30D4
CINEMATIC_081		EQU 0x311C
CINEMATIC_082		EQU 0x3168
CINEMATIC_083		EQU 0x31B4
CINEMATIC_084		EQU 0x2EF8
CINEMATIC_085		EQU 0x2EA8
CINEMATIC_086		EQU 0x2B50
CINEMATIC_087		EQU 0x2D2C
CINEMATIC_088		EQU 0x2C90
CINEMATIC_089		EQU 0x2CD8
CINEMATIC_090		EQU 0x2B9C
CINEMATIC_091		EQU 0x2D78
CINEMATIC_092		EQU 0x2BF4
CINEMATIC_093		EQU 0x2E10
CINEMATIC_094		EQU 0x2E5C
CINEMATIC_095		EQU 0x2DC0
CINEMATIC_096		EQU 0x2C40
CINEMATIC_097		EQU 0x3720
CINEMATIC_098		EQU 0x3764
CINEMATIC_099		EQU 0x37A8
CINEMATIC_100		EQU 0x37EC
CINEMATIC_101		EQU 0x345C
CINEMATIC_102		EQU 0x3508
CINEMATIC_103		EQU 0x35B4
CINEMATIC_104		EQU 0x3660
CINEMATIC_105		EQU 0x3848
CINEMATIC_106		EQU 0x3BA4
CINEMATIC_107		EQU 0x3BFA
CINEMATIC_108		EQU 0x000C
COMMON_VIDEO_129		EQU 0x1B14
COMMON_VIDEO_168		EQU 0x181C
COMMON_VIDEO_169		EQU 0x1A84
COMMON_VIDEO_171		EQU 0x1866
COMMON_VIDEO_172		EQU 0x18B0
COMMON_VIDEO_173		EQU 0x1AB4
COMMON_VIDEO_175		EQU 0x18FA
COMMON_VIDEO_176		EQU 0x1AE4
COMMON_VIDEO_178		EQU 0x1944
COMMON_VIDEO_180		EQU 0x198E
COMMON_VIDEO_181		EQU 0x1B44
COMMON_VIDEO_184		EQU 0x19C4
COMMON_VIDEO_185		EQU 0x1B74
COMMON_VIDEO_188		EQU 0x1A0E
COMMON_VIDEO_189		EQU 0x1BA4
COMMON_VIDEO_192		EQU 0x1D78
COMMON_VIDEO_193		EQU 0x1BD4
COMMON_VIDEO_195		EQU 0x1D9A
COMMON_VIDEO_196		EQU 0x1DBC
COMMON_VIDEO_197		EQU 0x1DDE
COMMON_VIDEO_198		EQU 0x1E00
COMMON_VIDEO_199		EQU 0x1E22
COMMON_VIDEO_200		EQU 0x1E44
COMMON_VIDEO_201		EQU 0x1E66
COMMON_VIDEO_202		EQU 0x1A54
COMMON_VIDEO_291		EQU 0x4346
COMMON_VIDEO_301		EQU 0x1C78


	org 0x0000

LABEL_0000:
	call LABEL_0B49
	setup channel=0x3C, address=LABEL_0AE0
	mov [PAUSE_SLICES], 0x0004
	break
	song id=0x0000, delay=0x0000, pos=0x00
	call PRELOAD_RESOURCES_8_TO_1
	call LABEL_0025
	setup channel=0x1E, address=LABEL_0676
	killChannel
	copyVideoPage src=0x00, dst=0x03
	killChannel
	copyVideoPage src=0x03, dst=0x00

LABEL_0024:
	killChannel

LABEL_0025:
	ret
	jne [0xF2], 0x0FA0, DELETE_ALL_CHANS_AND_KILL

DELETE_ALL_CHANS_AND_KILL:
	deleteChannels first=0x00, last=0x3F
	killChannel

PRELOAD_RESOURCES_8_TO_1:
	jne [0xDB], 0x00, LABEL_0060
	load id=0x0008
	load id=0x008A
	load id=0x0081
	load id=0x0082
	load id=0x0083
	load id=0x0080
	load id=0x0001
	load id=0x0057
	load id=0x005E
	load id=0x000E
	load id=0x000F
	load id=0x005F
	load id=0x000C
	ret

LABEL_0060:
	load id=0x07DF
	song id=0x0BDC, delay=0x0000, pos=0x00
	ret

LABEL_006A:
	video type=1, offset=CINEMATIC_097, x=160, y=100
	break
	video type=1, offset=CINEMATIC_098, x=160, y=100
	break
	video type=1, offset=CINEMATIC_099, x=160, y=100
	break
	video type=1, offset=CINEMATIC_100, x=160, y=100
	break
	video type=1, offset=CINEMATIC_099, x=160, y=100
	break
	video type=1, offset=CINEMATIC_098, x=160, y=100
	break
	jmp LABEL_006A
LABEL_008B:
	db 0x11

DRAW_CIN_101_102_FADE_PAL_C:
	video type=1, offset=CINEMATIC_101, x=160, y=125
	setPalette 0x0C
	break
	video type=1, offset=CINEMATIC_101, x=160, y=118
	break
	video type=1, offset=CINEMATIC_102, x=160, y=112
	break
	video type=1, offset=CINEMATIC_103, x=160, y=107
	break
	video type=1, offset=CINEMATIC_104, x=160, y=105
	break
	video type=1, offset=CINEMATIC_104, x=160, y=109
	break
	video type=1, offset=CINEMATIC_104, x=160, y=110
	break
	video type=1, offset=CINEMATIC_103, x=160, y=115

LABEL_00B6:
	break
	video type=1, offset=CINEMATIC_103, x=160, y=118
	jmp LABEL_00B6
LABEL_00BE:
	db 0x11

LABEL_00BF:
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	mov [0x03], 0x0040
	video type=1, offset=CINEMATIC_052, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_053, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_054, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_055, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_056, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_054, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_057, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_053, x=[0x01], y=[0x02], zoom=[0x03]
	deleteChannels first=0x0A, last=0x0E
	copyVideoPage src=0x03, dst=0x00
	setup channel=0x0A, address=LABEL_0159
	setup channel=0x0B, address=LABEL_011A
	setup channel=0x0E, address=LABEL_0504
	setup channel=0x0F, address=LABEL_0125
	killChannel

LABEL_011A:
	video type=1, offset=CINEMATIC_058, x=160, y=100, zoom=[0x04]
	break
	jmp LABEL_011A
LABEL_0124:
	db 0x11

LABEL_0125:
	video type=1, offset=CINEMATIC_059, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_060, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_061, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_062, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_063, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_064, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_065, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_0125

LABEL_0159:
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	mov [0x03], 0x0040
	mov [0x04], 0x0040
	setPalette 0x0B
	add [0x04], 0x0002
	video type=1, offset=CINEMATIC_067, x=[0x01], y=[0x02], zoom=[0x03]
	break
	add [0x04], 0x0005
	video type=1, offset=CINEMATIC_068, x=[0x01], y=[0x02], zoom=[0x03]
	break
	add [0x04], 0x0008
	video type=1, offset=CINEMATIC_069, x=[0x01], y=[0x02], zoom=[0x03]
	setup channel=0x0C, address=LABEL_0512
	setup channel=0x0D, address=LABEL_058D
	mov [0x06], 0x000A

LABEL_0198:
	break
	add [0x04], 0x000A
	djnz [0x06], LABEL_0198
	setup channel=0x0B, address=LABEL_0024
	mov [0x06], 0x0030

LABEL_01A9:
	break
	sub [0x03], 0x0001
	djnz [0x06], LABEL_01A9
	setup channel=0x10, address=INIT_VARE_TO_12
	setup channel=0x11, address=LABEL_0230
	mov [0x0F], 0x0001
	mov [0x06], 0x000C

LABEL_01C2:
	break
	break
	sub [0x03], 0x0001
	djnz [0x06], LABEL_01C2
	mov [0x06], 0x0019

LABEL_01D0:
	break
	djnz [0x06], LABEL_01D0
	sub [0x03], 0x0001
	mov [0x06], 0x0019

LABEL_01DD:
	break
	djnz [0x06], LABEL_01DD
	sub [0x03], 0x0001
	killChannel

INIT_VARE_TO_12:
	mov [0x0E], 0x000C

LABEL_01EB:
	break
	add [0x0F], 0x0001
	djnz [0x0E], LABEL_01EB
	mov [0x0E], 0x0009

LABEL_01F8:
	break
	add [0x0F], 0x0004
	djnz [0x0E], LABEL_01F8
	mov [0x0E], 0x0032

LABEL_0205:
	break
	djnz [0x0E], LABEL_0205
	mov [0x0E], 0x0005

LABEL_020E:
	break
	add [0x0F], 0x0008
	djnz [0x0E], LABEL_020E
	setup channel=0x36, address=LABEL_023B
	break
	add [0x0F], 0x000C
	break
	add [0x0F], 0x0018
	break
	add [0x0F], 0x0026
	break
	add [0x0F], 0x0038
	killChannel

LABEL_0230:
	video type=1, offset=CINEMATIC_070, x=[0x01], y=[0x02], zoom=[0x0f]
	break
	jmp LABEL_0230
LABEL_023A:
	db 0x11

LABEL_023B:
	setPalette 0x10
	break
	setPalette 0x11
	break
	setPalette 0x12
	break
	setPalette 0x13
	break
	setPalette 0x14
	break
	setPalette 0x15
	break
	setPalette 0x16
	break
	setPalette 0x17
	deleteChannels first=0x0A, last=0x11
	fill page=0x00, color=0x00
	fill page=0x03, color=0x00
	break
	jne [0xDB], 0x01, LABEL_035A
	selectVideoPage 0x00
	text id=0x0258, x=2, y=10, color=0x0C ; "Design ............... Eric Chahi"
	text id=0x0259, x=2, y=40, color=0x0C ; "Original Programmer .. Eric Chahi"
	text id=0x025A, x=2, y=70, color=0x0C ; "Genesis Programmer ... Michael Burton


Exec. Producer. Stephen Clarke-Willson"
	text id=0x025B, x=1, y=100, color=0x0C ; "
 U.K. Producer ........Matthew Spall
 Virgin Games, Inc. Producer . Erik Yeo
 Interplay Producer ...... Alan Pavlish

 Music ...... Tommy Tallarico
       ...... Jean-Francois Freitas

 Sound ...... Tommy Tallarico
       ...... Jean-Francois Freitas
       ...... Eric Chahi

"
	text id=0x025C, x=2, y=130, color=0x0C ; "string_025C"
	text id=0x025D, x=2, y=140, color=0x0C ; "string_025D"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	setup channel=0x3C, address=LABEL_0AF3
	mov [PAUSE_SLICES], 0x0002
	mov [0x01], 0x000A

LABEL_02A3:
	break
	djnz [0x01], LABEL_02A3
	setup channel=0x14, address=PAL_FADE_18_TO_1D
	mov [0x01], 0x00AF

LABEL_02B0:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02B0
	mov [0x01], 0x00C8

LABEL_02BD:
	break
	djnz [0x01], LABEL_02BD
	mov [0x01], 0x00B4

LABEL_02C6:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02C6
	selectVideoPage 0x00
	fill page=0x00, color=0x00
	text id=0x0263, x=6, y=0, color=0x0C ; "Title Animation . Jason Magness

Q.A. Manager .... Michael Gater

"
	text id=0x0264, x=6, y=30, color=0x0C ; "
Quality Assurance Team 

Noah Tool     Justin Norr
Danny Lewis   Mike Glosecki
Eugene Martin Tommy Hulett
Joey Kuras    Tim Williams

Manual ...Robin Kausch

Thanks to 

Jesus Martinez     Daniel Morais
Frederic Savoir    Cecile Chahi
Philippe Delamarre Philippe Ulrich
Sebastien Berthet  Pierre Gousseau
Bill Heineman      Jason Ferris
"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	mov [0x01], 0x0096

LABEL_02EA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_02EA
	mov [0x01], 0x00C8

LABEL_02F7:
	break
	djnz [0x01], LABEL_02F7
	mov [0x01], 0x00C8

LABEL_0300:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0300
	selectVideoPage 0x00
	fill page=0x00, color=0x00
	text id=0x0265, x=6, y=0, color=0x0C ; "   Now Go Out Of This World"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x00C8
	mov [0x01], 0x0064

LABEL_031E:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_031E
	mov [0x01], 0x00AA

LABEL_032B:
	break
	djnz [0x01], LABEL_032B
	GameOver
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	selectVideoPage 0x00
	text id=0x017C, x=9, y=10, color=0x0C ; "string_017C"
	text id=0x017D, x=19, y=40, color=0x05 ; "string_017D"
	text id=0x017E, x=13, y=90, color=0x0B ; "string_017E"
	text id=0x0180, x=12, y=120, color=0x0D ; "string_0180"
	text id=0x017F, x=12, y=150, color=0x0E ; "string_017F"
	selectVideoPage 0xFF
	killChannel

LABEL_035A:
	load id=0x3E89
	killChannel
	selectVideoPage 0x03
	text id=0x0258, x=2, y=20, color=0x0C ; "Design ............... Eric Chahi"
	text id=0x0259, x=2, y=50, color=0x0C ; "Original Programmer .. Eric Chahi"
	text id=0x025A, x=2, y=80, color=0x0C ; "Genesis Programmer ... Michael Burton


Exec. Producer. Stephen Clarke-Willson"
	text id=0x025B, x=2, y=130, color=0x0C ; "
 U.K. Producer ........Matthew Spall
 Virgin Games, Inc. Producer . Erik Yeo
 Interplay Producer ...... Alan Pavlish

 Music ...... Tommy Tallarico
       ...... Jean-Francois Freitas

 Sound ...... Tommy Tallarico
       ...... Jean-Francois Freitas
       ...... Eric Chahi

"
	selectVideoPage 0xFF
	mov [SCROLL_Y], 0x0000
	setup channel=0x3C, address=LABEL_0B01
	mov [PAUSE_SLICES], 0x0002
	mov [0x01], 0x000A

LABEL_038A:
	break
	djnz [0x01], LABEL_038A
	setup channel=0x14, address=PAL_FADE_18_TO_1D
	mov [0x01], 0x00C8

LABEL_0397:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0397
	selectVideoPage 0x00
	text id=0x025C, x=2, y=2, color=0x0C ; "string_025C"
	text id=0x025E, x=2, y=82, color=0x0C ; "string_025E"
	text id=0x025F, x=2, y=162, color=0x0C ; "string_025F"
	selectVideoPage 0xFF
	mov [0x01], 0x00C8

LABEL_03BA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03BA
	fill page=0x03, color=0x00
	selectVideoPage 0x03
	text id=0x0260, x=2, y=45, color=0x0C ; "string_0260"
	text id=0x0261, x=2, y=172, color=0x0C ; "string_0261"
	selectVideoPage 0xFF
	mov [0x01], 0x00C8

LABEL_03DA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03DA
	fill page=0x00, color=0x00
	mov [0x01], 0x00C8

LABEL_03EA:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_03EA
	fill page=0x03, color=0x00
	selectVideoPage 0x03
	text id=0x0263, x=5, y=50, color=0x0C ; "Title Animation . Jason Magness

Q.A. Manager .... Michael Gater

"
	text id=0x0264, x=2, y=90, color=0x0C ; "
Quality Assurance Team 

Noah Tool     Justin Norr
Danny Lewis   Mike Glosecki
Eugene Martin Tommy Hulett
Joey Kuras    Tim Williams

Manual ...Robin Kausch

Thanks to 

Jesus Martinez     Daniel Morais
Frederic Savoir    Cecile Chahi
Philippe Delamarre Philippe Ulrich
Sebastien Berthet  Pierre Gousseau
Bill Heineman      Jason Ferris
"
	selectVideoPage 0xFF
	sub [SCROLL_Y], 0x0032
	mov [0x01], 0x0096

LABEL_040E:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_040E
	mov [0x01], 0x0028

LABEL_041B:
	break
	djnz [0x01], LABEL_041B
	fill page=0x00, color=0x00
	mov [0x01], 0x00BE

LABEL_0427:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0427
	sub [SCROLL_Y], 0x000A
	selectVideoPage 0x03
	fill page=0x03, color=0x00
	text id=0x0265, x=6, y=0, color=0x0C ; "   Now Go Out Of This World"
	selectVideoPage 0xFF
	mov [0x01], 0x0064

LABEL_0445:
	break
	sub [SCROLL_Y], 0x0001
	djnz [0x01], LABEL_0445
	mov [0x01], 0x0096
	GameOver
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel
	killChannel

PAL_FADE_18_TO_1D:
	setPalette 0x18
	break
	setPalette 0x19
	break
	setPalette 0x1A
	break
	setPalette 0x1B
	break
	setPalette 0x1C
	break
	setPalette 0x1D
	killChannel
	setPalette 0x1D
	break
	setPalette 0x1C
	break
	setPalette 0x1B
	break
	setPalette 0x1A
	break
	setPalette 0x19
	break
	setPalette 0x18
	break
	setPalette 0x17
	killChannel

DRAW_CIN_71_72_FADE:
	video type=1, offset=CINEMATIC_071, x=160, y=100
	break
	video type=1, offset=CINEMATIC_071, x=160, y=100
	break
	video type=1, offset=CINEMATIC_071, x=160, y=100
	break
	video type=1, offset=CINEMATIC_072, x=160, y=100
	break
	video type=1, offset=CINEMATIC_072, x=160, y=100
	break
	video type=1, offset=CINEMATIC_073, x=160, y=100
	break
	video type=1, offset=CINEMATIC_073, x=160, y=100

LABEL_04B5:
	break
	video type=1, offset=CINEMATIC_074, x=160, y=100
	jmp LABEL_04B5
LABEL_04BD:
	db 0x06

LABEL_04BE:
	video type=1, offset=CINEMATIC_071, x=160, y=100
	break
	jmp LABEL_04BE

DRAW_CIN_106_107_FX_57:
	video type=1, offset=CINEMATIC_106, x=160, y=100
	break
	video type=1, offset=CINEMATIC_106, x=160, y=100
	break
	play id=0x0057, freq=0x22, vol=0x20, channel=0x03
	video type=1, offset=CINEMATIC_107, x=160, y=100
	break
	video type=1, offset=CINEMATIC_107, x=160, y=100
	break
	video type=1, offset=CINEMATIC_107, x=160, y=100
	break
	video type=1, offset=CINEMATIC_107, x=160, y=100
	break
	video type=1, offset=CINEMATIC_106, x=160, y=100

LABEL_04EE:
	break
	video type=1, offset=CINEMATIC_074, x=160, y=100
	jmp LABEL_04EE
LABEL_04F6:
	db 0x11

LABEL_04F7:
	video type=1, offset=CINEMATIC_105, x=160, y=100
	add [0x03], 0x0002
	break
	jmp LABEL_04F7
LABEL_0503:
	db 0x11

LABEL_0504:
	video type=1, offset=CINEMATIC_066, x=[0x01], y=[0x02], zoom=[0x03]
	add [0x03], 0x0000
	break
	jmp LABEL_0504

LABEL_0512:
	video type=1, offset=CINEMATIC_086, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_087, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_088, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_089, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_090, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_091, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_092, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_093, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_094, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_092, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_091, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_090, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_089, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_088, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_087, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_095, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_096, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_0512
LABEL_058C:
	db 0x11

LABEL_058D:
	video type=1, offset=CINEMATIC_075, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_076, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_077, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_078, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_079, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_080, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_081, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_082, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_083, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_081, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_080, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_079, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_078, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_077, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_076, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_084, x=[0x01], y=[0x02], zoom=[0x03]
	break
	video type=1, offset=CINEMATIC_085, x=[0x01], y=[0x02], zoom=[0x03]
	break
	jmp LABEL_058D
LABEL_0607:
	db 0x11

SET_VAR_E6_5_PAL_B:
	mov [0xE6], 0x0005
	setPalette 0x0B

LABEL_060F:
	video type=1, offset=CINEMATIC_042, x=160, y=100
	break
	djnz [0xE6], LABEL_060F
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	video type=1, offset=CINEMATIC_043, x=160, y=100
	break
	video type=1, offset=CINEMATIC_044, x=160, y=100
	break
	video type=1, offset=CINEMATIC_045, x=160, y=100
	break
	video type=1, offset=CINEMATIC_046, x=160, y=100
	mov [0xE6], 0x0007

LABEL_0635:
	break
	video type=1, offset=CINEMATIC_046, x=160, y=100
	djnz [0xE6], LABEL_0635
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	break
	video type=1, offset=CINEMATIC_047, x=160, y=100
	break
	video type=1, offset=CINEMATIC_048, x=160, y=100
	break
	video type=1, offset=CINEMATIC_049, x=160, y=100
	break
	video type=1, offset=CINEMATIC_050, x=160, y=100
	mov [0xE6], 0x000A

LABEL_065C:
	break
	video type=1, offset=CINEMATIC_051, x=160, y=100
	djnz [0xE6], LABEL_065C
	setup channel=0x0A, address=LABEL_04F7
	setup channel=0x0B, address=DRAW_CIN_101_102_FADE_PAL_C
	setup channel=0x0C, address=LABEL_006A
	setup channel=0x0D, address=LABEL_00BF
	killChannel

LABEL_0676:
	call DRAW_STARS_PAGE0_CIN_000
	call DRAW_STARS_PAGE3_CIN_004
	setup channel=0x05, address=LABEL_04BE
	selectVideoPage 0x00
	play id=0x0008, freq=0x05, vol=0x20, channel=0x00
	play id=0x0008, freq=0x07, vol=0x30, channel=0x01
	video type=1, offset=CINEMATIC_008, x=160, y=100
	video type=1, offset=CINEMATIC_009, x=160, y=100
	video type=1, offset=CINEMATIC_010, x=160, y=100
	selectVideoPage 0xFF
	mov [PAUSE_SLICES], 0x0004
	mov [0x03], 0x000A
	mov [0x01], 0x00A0
	mov [0x02], 0x0064
	setPalette 0x0A

LABEL_06AF:
	break
	djnz [0x03], LABEL_06AF
	setup channel=0x05, address=DRAW_CIN_71_72_FADE
	video type=1, offset=CINEMATIC_011, x=[0x01], y=[0x02], zoom=0x40
	play id=0x0008, freq=0x0A, vol=0x16, channel=0x00
	play id=0x0057, freq=0x14, vol=0x20, channel=0x02
	break
	video type=1, offset=CINEMATIC_012, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_013, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	play id=0x000E, freq=0x03, vol=0x20, channel=0x03
	mov [0x03], 0x0014

LABEL_06E5:
	break
	video type=1, offset=CINEMATIC_015, x=[0x01], y=[0x02], zoom=0x40
	djnz [0x03], LABEL_06E5
	mov [PAUSE_SLICES], 0x000A
	mov [0x03], 0x0006
	play id=0x000F, freq=0x03, vol=0x30, channel=0x03
	break
	play id=0x0008, freq=0x07, vol=0x11, channel=0x01

LABEL_0704:
	video type=1, offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	jne [0x03], 0x04, LABEL_0722
	song id=0x008A, delay=0x3A98, pos=0x00
	play id=0x0008, freq=0x0A, vol=0x16, channel=0x00

LABEL_0722:
	jne [0x03], 0x03, LABEL_072E
	play id=0x0008, freq=0x0A, vol=0x0B, channel=0x00

LABEL_072E:
	video type=1, offset=CINEMATIC_013, x=[0x01], y=[0x02], zoom=0x40
	break
	add [0x01], 0x0002
	video type=1, offset=CINEMATIC_016, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_016, x=[0x01], y=[0x02], zoom=0x40
	break
	add [0x01], 0x0001
	video type=1, offset=CINEMATIC_017, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_017, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_018, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_015, x=[0x01], y=[0x02], zoom=0x40
	break
	video type=1, offset=CINEMATIC_014, x=[0x01], y=[0x02], zoom=0x40
	break
	add [PAUSE_SLICES], 0x0002
	djnz [0x03], LABEL_0704
	mov [PAUSE_SLICES], 0x0006
	video type=1, offset=CINEMATIC_019, x=[0x01], y=[0x02], zoom=0x40
	setup channel=0x14, address=INIT_VARS_07_08_09

LABEL_0787:
	break
	video type=1, offset=CINEMATIC_020, x=[0x01], y=[0x02], zoom=0x40
	jmp LABEL_0787
LABEL_0790:
	db 0x11

INIT_VARS_07_08_09:
	mov [0x07], 0x004C
	mov [0x08], 0x0097
	mov [0x09], 0x0003

LABEL_079D:
	break
	djnz [0x09], LABEL_079D
	play id=0x0057, freq=0x0F, vol=0x20, channel=0x03
	video type=1, offset=CINEMATIC_021, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_022, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_023, x=[0x07], y=[0x08], zoom=0x40
	mov [0x09], 0x000A

LABEL_07BD:
	break
	video type=1, offset=CINEMATIC_024, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_025, x=[0x07], y=[0x08], zoom=0x40
	djnz [0x09], LABEL_07BD
	setup channel=0x11, address=LABEL_085E
	setup channel=0x12, address=LABEL_0868
	setup channel=0x13, address=LABEL_08CC
	setup channel=0x0C, address=LABEL_0930
	mov [0x09], 0x0010

LABEL_07E0:
	break
	djnz [0x09], LABEL_07E0
	setup channel=0x0C, address=LABEL_0024
	deleteChannels first=0x11, last=0x13
	break
	video type=1, offset=CINEMATIC_026, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_027, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_028, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_029, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_030, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_031, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x05, address=DRAW_CIN_106_107_FX_57
	mov [0x09], 0x000A

LABEL_0819:
	break
	video type=1, offset=CINEMATIC_032, x=[0x07], y=[0x08], zoom=0x40
	djnz [0x09], LABEL_0819
	setup channel=0x1E, address=LABEL_0024
	break
	video type=1, offset=CINEMATIC_033, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_034, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_035, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_036, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_037, x=[0x07], y=[0x08], zoom=0x40
	selectVideoPage 0x00
	fill page=0x00, color=0x01
	call DRAW_STARS_CIN_38_39_40_5_6
	selectVideoPage 0xFF
	setup channel=0x05, address=LABEL_0024
	setup channel=0x0A, address=SET_VAR_E6_5_PAL_B
	killChannel

LABEL_085E:
	video type=1, offset=CINEMATIC_024, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_085E
LABEL_0867:
	db 0x11

LABEL_0868:
	video type=0, offset=COMMON_VIDEO_192, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_195, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_196, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_197, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_198, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_199, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_200, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_201, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_168, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_171, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_172, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_175, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_178, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_180, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_184, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_188, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_0868
LABEL_08CB:
	db 0x11

LABEL_08CC:
	video type=0, offset=COMMON_VIDEO_193, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_185, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_181, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_129, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_176, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_173, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_202, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_202, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_169, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_169, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_173, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_176, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_129, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_181, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_185, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=0, offset=COMMON_VIDEO_189, x=[0x07], y=[0x08], zoom=0x40
	break
	jmp LABEL_08CC
LABEL_092F:
	db 0x11

LABEL_0930:
	mov [0x0A], 0x0003
	add [0x07], 0x0002
	break
	djnz [0x0A], LABEL_0930
	mov [0x0A], 0x0005

LABEL_0941:
	add [0x07], 0x0003
	break
	djnz [0x0A], LABEL_0941
	jmp LABEL_0930
	killChannel
	video type=1, offset=CINEMATIC_108, x=160, y=100
	video type=0, offset=COMMON_VIDEO_301, x=160, y=100, zoom=0x40
	video type=0, offset=COMMON_VIDEO_291, x=160, y=100, zoom=0x40
	video type=0, offset=COMMON_VIDEO_202, x=160, y=100, zoom=0x40
	killChannel

DRAW_STARS_PAGE0_CIN_000:
	selectVideoPage 0x00
	fill page=0x00, color=0x01
	video type=1, offset=CINEMATIC_000, x=253, y=34, zoom=[0x0a]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=269, y=29, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=273, y=78, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=303, y=57, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=140, y=79, zoom=[0x08]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=214, y=85, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=66, y=79, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=111, y=52, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=95, y=103, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=153, y=89, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=132, y=107, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=4, y=85, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=65, y=115, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=293, y=139, zoom=0x40
	video type=1, offset=CINEMATIC_000, x=11, y=109, zoom=[0x1c]	;@enc=alt
	video type=1, offset=CINEMATIC_000, x=11, y=146
	video type=1, offset=CINEMATIC_001, x=31, y=187
	video type=1, offset=CINEMATIC_002, x=301, y=14, zoom=0x40
	video type=1, offset=CINEMATIC_001, x=294, y=188, zoom=0x40
	video type=1, offset=CINEMATIC_003, x=2, y=167
	video type=1, offset=CINEMATIC_002, x=92, y=30
	video type=1, offset=CINEMATIC_002, x=128, y=11
	video type=1, offset=CINEMATIC_002, x=166, y=10
	video type=1, offset=CINEMATIC_002, x=85, y=19
	video type=1, offset=CINEMATIC_002, x=48, y=12
	video type=1, offset=CINEMATIC_002, x=111, y=3
	video type=1, offset=CINEMATIC_002, x=13, y=11, zoom=[0x20]	;@enc=alt
	selectVideoPage 0xFF
	ret
LABEL_09F7:
	db 0x11

DRAW_STARS_PAGE3_CIN_004:
	selectVideoPage 0x03
	fill page=0x03, color=0x01
	video type=1, offset=CINEMATIC_004, x=253, y=34, zoom=[0x0a]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=269, y=29, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=273, y=78, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=303, y=57, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=140, y=79, zoom=[0x08]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=214, y=85, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=66, y=79, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=111, y=52, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=95, y=103, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=153, y=89, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=132, y=107, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=4, y=85, zoom=[0x10]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=65, y=115, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=293, y=139, zoom=0x40
	video type=1, offset=CINEMATIC_004, x=11, y=109, zoom=[0x1c]	;@enc=alt
	video type=1, offset=CINEMATIC_004, x=11, y=146
	video type=1, offset=CINEMATIC_005, x=31, y=187
	video type=1, offset=CINEMATIC_006, x=301, y=14, zoom=0x40
	video type=1, offset=CINEMATIC_005, x=294, y=188, zoom=0x40
	video type=1, offset=CINEMATIC_007, x=2, y=167
	video type=1, offset=CINEMATIC_006, x=92, y=30
	video type=1, offset=CINEMATIC_006, x=128, y=11
	video type=1, offset=CINEMATIC_006, x=166, y=10
	video type=1, offset=CINEMATIC_006, x=85, y=19
	video type=1, offset=CINEMATIC_006, x=48, y=12
	video type=1, offset=CINEMATIC_006, x=111, y=3
	video type=1, offset=CINEMATIC_006, x=13, y=11, zoom=[0x20]	;@enc=alt
	selectVideoPage 0xFF
	ret
LABEL_0A8D:
	db 0x11

DRAW_STARS_CIN_38_39_40_5_6:
	video type=1, offset=CINEMATIC_006, x=126, y=25
	video type=1, offset=CINEMATIC_038, x=133, y=102, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_038, x=129, y=114, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_038, x=114, y=126, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_006, x=91, y=8, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_039, x=16, y=114
	video type=1, offset=CINEMATIC_039, x=74, y=177, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_040, x=78, y=166
	video type=1, offset=CINEMATIC_005, x=283, y=175, zoom=0x40
	video type=1, offset=CINEMATIC_005, x=294, y=183, zoom=0x40
	video type=1, offset=CINEMATIC_005, x=58, y=185
	video type=1, offset=CINEMATIC_005, x=5, y=170
	video type=1, offset=CINEMATIC_041, x=197, y=160, zoom=[0x20]	;@enc=alt
	video type=1, offset=CINEMATIC_041, x=61, y=169
	video type=1, offset=CINEMATIC_041, x=300, y=28, zoom=0x40
	video type=1, offset=CINEMATIC_041, x=202, y=86, zoom=[0x30]	;@enc=alt
	ret

LABEL_0AE0:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	break
	jmp LABEL_0AE0

JUNK__0AEB:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	break
	jmp JUNK__0AEB

LABEL_0AF3:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	fill page=0xFF, color=0x00
	copyVideoPage src=0x80, dst=0xFF
	break
	jmp LABEL_0AF3

LABEL_0B01:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	jg [SCROLL_Y], 0xFF38, LABEL_0B13
	add [SCROLL_Y], 0x00C8
	jmp LABEL_0B37

LABEL_0B13:
	copyVideoPage src=0x80, dst=0xFF
	add [SCROLL_Y], 0x00C8
	copyVideoPage src=0x83, dst=0xFF
	sub [SCROLL_Y], 0x00C8
	break
	jmp LABEL_0B01

LABEL_0B25:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	jg [SCROLL_Y], 0xFF38, LABEL_0B37
	add [SCROLL_Y], 0x00C8
	jmp LABEL_0B13

LABEL_0B37:
	copyVideoPage src=0x83, dst=0xFF
	add [SCROLL_Y], 0x00C8
	copyVideoPage src=0x80, dst=0xFF
	sub [SCROLL_Y], 0x00C8
	break
	jmp LABEL_0B25

LABEL_0B49:
	fill page=0x01, color=0x00
	fill page=0x02, color=0x00
	selectVideoPage 0x01
	blitFramebuffer 0x01
	blitFramebuffer 0xFF
	blitFramebuffer 0x02
	ret
LABEL_0B58:
	db 0x11, 0x11, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
	FILL(62624, 0xFF)
