; STAGE PASSCODE: password-entry screen for save-state restoration.
;
; Gameplay role: shown before the game starts (or between sessions)
; to let players resume from a stored checkpoint. Hashes the entered
; characters into per-stage save vectors. Replaces the checkpoint
; system on platforms without battery-backed save.
;
; This file: cartridge_1992 (Heineman SNES + Genesis port)
;
;
; Smallest unified file (only 6 folded bodies). The hashing logic
; (SUM_HASH_VARS_TO_VAR_37) is one of the most analyzed routines
; in the genealogy work — it's structurally identical across all
; three branches.
;
; Generated by AnotherWorld_VMTools
;@include "../_common_vars.inc"
CINEMATIC_000		EQU 0x0298
CINEMATIC_001		EQU 0x02D8
CINEMATIC_002		EQU 0x0188
CINEMATIC_003		EQU 0x01CC
CINEMATIC_004		EQU 0x000C
CINEMATIC_005		EQU 0x0020


	org 0x0000

LABEL_0000:
	call LABEL_0BD2
	mov [PAUSE_SLICES], 0x0002
	setup channel=0x3C, address=LABEL_0BBF
	fill page=0x00, color=0x00
	fill page=0xFF, color=0x00
	mov [LAST_KEYCHAR], 0x0000
	break
	fill page=0x00, color=0x00
	setup channel=0x14, address=LABEL_00B0
	killChannel

AMIGA_PASSCODE_BANK_INIT:
	killChannel

LABEL_001F:
	jne [0x05], 0x00, LABEL_0028
	mov [0x06], [0x0A]

LABEL_0028:
	jne [0x05], 0x01, LABEL_0031
	mov [0x06], [0x0B]

LABEL_0031:
	jne [0x05], 0x02, LABEL_003A
	mov [0x06], [0x0C]

LABEL_003A:
	jne [0x05], 0x03, LABEL_0043
	mov [0x06], [0x0D]

LABEL_0043:
	jne [0x05], 0x04, LABEL_004C
	mov [0x06], [0x0E]

LABEL_004C:
	jne [0x05], 0x05, LABEL_0055
	mov [0x06], [0x0F]

LABEL_0055:
	jne [0x05], 0x06, LABEL_005E
	mov [0x06], [0x10]

LABEL_005E:
	jne [0x05], 0x07, LOAD_VAR12_TO_VAR06
	mov [0x06], [0x11]

LOAD_VAR12_TO_VAR06:
	jne [0x05], 0x08, LOAD_VAR13_TO_VAR06
	mov [0x06], [0x12]

LOAD_VAR13_TO_VAR06:
	jne [0x05], 0x09, LOAD_VAR14_TO_VAR06
	mov [0x06], [0x13]

LOAD_VAR14_TO_VAR06:
	jne [0x05], 0x0A, LOAD_VAR15_TO_VAR06
	mov [0x06], [0x14]

LOAD_VAR15_TO_VAR06:
	jne [0x05], 0x0B, LOAD_VAR16_TO_VAR06
	mov [0x06], [0x15]

LOAD_VAR16_TO_VAR06:
	jne [0x05], 0x0C, LOAD_VAR17_TO_VAR06
	mov [0x06], [0x16]

LOAD_VAR17_TO_VAR06:
	jne [0x05], 0x0D, LOAD_VAR18_TO_VAR06
	mov [0x06], [0x17]

LOAD_VAR18_TO_VAR06:
	jne [0x05], 0x0E, LOAD_VAR19_TO_VAR06
	mov [0x06], [0x18]

LOAD_VAR19_TO_VAR06:
	jne [0x05], 0x0F, SHARED_RET
	mov [0x06], [0x19]
	ret

LABEL_00B0:
	mov [0x09], 0x0010
	fill page=0xFF, color=0x00
	mov [0x04], 0x0040
	mov [0x02], 0x0000
	mov [0x05], [0x37]
	and [0x05], 0x000F
	mov [0x2F], [0x05]
	call LABEL_01A0
	mov [0x2D], 0x0072
	mov [0x2E], 0x003E
	mov [0x19], 0x0062
	mov [0x11], 0x0063
	mov [0x1E], 0xFFFF
	mov [0x1F], 0xFFFF
	mov [0x20], 0xFFFF
	mov [0x21], 0xFFFF
	mov [0x05], 0x0000
	selectVideoPage 0x00
	text id=0x013E, x=4, y=70, color=0x00 ; "   ENTER ACCESS CODE"
	text id=0x013C, x=2, y=80, color=0x06 ; "        ACCESS CODE:"
	call INIT_BITMASKS_BC_C6
	selectVideoPage 0xFF

LABEL_0103:
	call LABEL_001F
	selectVideoPage 0x00
	call LABEL_0334
	selectVideoPage 0xFF
	add [0x05], 0x0001
	djnz [0x09], LABEL_0103
	je [0xDB], 0x00, LABEL_012B
	selectVideoPage 0x00
	text id=0x012C, x=7, y=130, color=0x04 ; "    B C D F G H"
	text id=0x012D, x=7, y=146, color=0x04 ; "    J K L R T X"
	selectVideoPage 0xFF

LABEL_012B:
	mov [0x01], 0x0003
	mov [0x07], 0x00A0
	mov [0x08], 0x0064
	mov [0x05], [0x01]
	call LABEL_08CD
	setPalette 0x05	;@raw=0x0B,0x05,0xFF
	copyVideoPage src=0x00, dst=0xFF
	jmp LABEL_033B
LABEL_0146:
	db 0x11

INIT_BITMASKS_BC_C6:
	and [0xBC], 0x0010
	and [0xC6], 0x0080
	ret
	jmp ENTRY_2ND_PASSCODE_INSTANCE
	je [0xBC], 0x00, DRAW_PROGRESS_MARKERS
	video type=1, offset=CINEMATIC_005, x=0, y=0	;@raw=0x80,0x10,0x00,0x00

DRAW_PROGRESS_MARKERS:
	je [0xC6], 0x00, LABEL_0167
	video type=1, offset=CINEMATIC_005, x=16, y=0	;@raw=0x80,0x10,0x10,0x00

LABEL_0167:
	jne [0xF2], 0x0FA0, LABEL_0172
	video type=1, offset=CINEMATIC_005, x=0, y=16	;@raw=0x80,0x10,0x00,0x10

LABEL_0172:
	jne [HACK_VAR_DC], 0x21, TRIVIAL_RET
	video type=1, offset=CINEMATIC_005, x=16, y=16	;@raw=0x80,0x10,0x10,0x10

TRIVIAL_RET:
	ret

ENTRY_2ND_PASSCODE_INSTANCE:
	je [0xBC], 0x00, KILL_ALL_CHANNELS_AND_KILL
	je [0xC6], 0x00, KILL_ALL_CHANNELS_AND_KILL
	jne [0xF2], 0x0FA0, KILL_ALL_CHANNELS_AND_KILL
	jne [HACK_VAR_DC], 0x21, KILL_ALL_CHANNELS_AND_KILL
	ret

KILL_ALL_CHANNELS_AND_KILL:
	deleteChannels first=0x00, last=0x3F
	setup channel=0x3C, address=AMIGA_PASSCODE_BANK_INIT
	killChannel

LABEL_01A0:
	mov [0x2C], 0x0000
	mov [0x0A], 0x000B
	mov [0x0B], 0x000C
	mov [0x0C], 0x000D
	mov [0x0D], 0x000F
	mov [0x0E], 0x0010
	mov [0x0F], 0x0011
	mov [0x10], 0xFFFF
	mov [0x11], 0x0000
	mov [0x12], 0x0013
	mov [0x13], 0x0014
	mov [0x14], 0x0015
	mov [0x15], 0x001B
	mov [0x16], 0x001D
	mov [0x17], 0x0021
	mov [0x18], 0xFFFF
	mov [0x19], 0x0000
	ret
	mov [0x0A], [0x29]
	mov [0x0C], [0x2A]
	mov [0x14], [0x2B]
	mov [0x17], [0x2C]
	ret
	jne [0x22], 0x00, LABEL_01FC
	mov [0x1D], [0x0A]
	ret

LABEL_01FC:
	jne [0x22], 0x01, LABEL_0206
	mov [0x1D], [0x0B]
	ret

LABEL_0206:
	jne [0x22], 0x02, LABEL_0210
	mov [0x1D], [0x0C]
	ret

LABEL_0210:
	jne [0x22], 0x03, LABEL_021A
	mov [0x1D], [0x0D]
	ret

LABEL_021A:
	jne [0x22], 0x04, LABEL_0224
	mov [0x1D], [0x0E]
	ret

LABEL_0224:
	jne [0x22], 0x05, LABEL_022E
	mov [0x1D], [0x0F]
	ret

LABEL_022E:
	jne [0x22], 0x06, LABEL_0238
	mov [0x1D], [0x10]
	ret

LABEL_0238:
	jne [0x22], 0x07, LABEL_0242
	mov [0x1D], [0x11]
	ret

LABEL_0242:
	jne [0x22], 0x08, LABEL_024C
	mov [0x1D], [0x12]
	ret

LABEL_024C:
	jne [0x22], 0x09, LABEL_0256
	mov [0x1D], [0x13]
	ret

LABEL_0256:
	jne [0x22], 0x0A, LABEL_0260
	mov [0x1D], [0x14]
	ret

LABEL_0260:
	jne [0x22], 0x0B, LABEL_026A
	mov [0x1D], [0x15]
	ret

LABEL_026A:
	jne [0x22], 0x0C, LABEL_0274
	mov [0x1D], [0x16]
	ret

LABEL_0274:
	jne [0x22], 0x0D, LABEL_027E
	mov [0x1D], [0x17]
	ret

LABEL_027E:
	jne [0x22], 0x0E, LABEL_0288
	mov [0x1D], [0x18]
	ret

LABEL_0288:
	jne [0x22], 0x0F, SHARED_RET
	mov [0x1D], [0x19]
	ret
	killChannel
	jne [0x22], 0x00, LABEL_029D
	mov [0x0A], [0x1D]
	ret

LABEL_029D:
	jne [0x22], 0x01, LABEL_02A7
	mov [0x0B], [0x1D]
	ret

LABEL_02A7:
	jne [0x22], 0x02, LABEL_02B1
	mov [0x0C], [0x1D]
	ret

LABEL_02B1:
	jne [0x22], 0x03, LABEL_02BB
	mov [0x0D], [0x1D]
	ret

LABEL_02BB:
	jne [0x22], 0x04, LABEL_02C5
	mov [0x0E], [0x1D]
	ret

LABEL_02C5:
	jne [0x22], 0x05, LABEL_02CF
	mov [0x0F], [0x1D]
	ret

LABEL_02CF:
	jne [0x22], 0x06, LABEL_02D9
	mov [0x10], [0x1D]
	ret

LABEL_02D9:
	jne [0x22], 0x07, SAVE_HASH_VAR1D_TO_VAR12
	mov [0x11], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR12:
	jne [0x22], 0x08, SAVE_HASH_VAR1D_TO_VAR13
	mov [0x12], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR13:
	jne [0x22], 0x09, SAVE_HASH_VAR1D_TO_VAR14
	mov [0x13], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR14:
	jne [0x22], 0x0A, SAVE_HASH_VAR1D_TO_VAR15
	mov [0x14], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR15:
	jne [0x22], 0x0B, SAVE_HASH_VAR1D_TO_VAR16
	mov [0x15], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR16:
	jne [0x22], 0x0C, SAVE_HASH_VAR1D_TO_VAR17
	mov [0x16], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR17:
	jne [0x22], 0x0D, SAVE_HASH_VAR1D_TO_VAR18
	mov [0x17], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR18:
	jne [0x22], 0x0E, SAVE_HASH_VAR1D_TO_VAR19
	mov [0x18], [0x1D]
	ret

SAVE_HASH_VAR1D_TO_VAR19:
	jne [0x22], 0x0F, SHARED_RET
	mov [0x19], [0x1D]
	ret
LABEL_0333:
	db 0x11

LABEL_0334:
	call LABEL_08CD
	call LABEL_0B8D
	ret

LABEL_033B:
	jne [LAST_KEYCHAR], 0x00, LABEL_07F1
	je [0xDB], 0x00, LABEL_0352
	jne [HERO_POS_JUMP_DOWN], 0xFFFF, LABEL_0352
	mov [HERO_ACTION], 0x0001

LABEL_0352:
	jne [HERO_ACTION], 0x00, LABEL_07F1
	mov [0x23], [0x01]
	jne [HERO_POS_UP_DOWN], 0x01, LABEL_036E
	jg [0x01], 0x07, LABEL_037F
	add [0x01], 0x0008
	jmp LABEL_037F

LABEL_036E:
	jne [HERO_POS_UP_DOWN], 0xFFFF, LABEL_037F
	jl [0x01], 0x08, LABEL_037F
	sub [0x01], 0x0008

LABEL_037F:
	jmp LABEL_03A7
	jne [HERO_POS_LEFT_RIGHT], 0x01, LABEL_0394
	je [0x01], 0x07, LABEL_03C0
	je [0x01], 0x0F, LABEL_03C0

LABEL_0394:
	jne [HERO_POS_LEFT_RIGHT], 0xFFFF, LABEL_03A7
	je [0x01], 0x00, LABEL_03C0
	je [0x01], 0x08, LABEL_03C0

LABEL_03A7:
	add [0x01], [HERO_POS_LEFT_RIGHT]
	and [0x01], 0x000F
	jne [0x01], 0x06, LABEL_03B7
	add [0x01], [HERO_POS_LEFT_RIGHT]

LABEL_03B7:
	jne [0x01], 0x0E, LABEL_03C0
	add [0x01], [HERO_POS_LEFT_RIGHT]

LABEL_03C0:
	mov [0x05], [0x01]
	mov [0x25], [0x07]
	mov [0x26], [0x08]
	call LABEL_08CD
	mov [0x27], [0x07]
	mov [0x28], [0x08]
	jne [0x25], [0x27], LABEL_03E8
	jne [0x26], [0x28], LABEL_03E8
	video type=1, offset=CINEMATIC_002, x=[0x07], y=[0x08], zoom=0x40	;@raw=0x54,0x00,0xC4,0x07,0x08
	break
	jmp LABEL_033B
LABEL_03E7:
	db 0x11

LABEL_03E8:
	mov [0x07], [0x25]
	mov [0x08], [0x26]
	mov [0x24], 0x0003
	jmp COPY_VAR_27_28_TO_07_08

JUNK__03F5:
	jg [0x25], [0x27], LABEL_0407
	add [0x07], [0x24]
	jl [0x07], [0x27], LABEL_0407
	mov [0x07], [0x27]

LABEL_0407:
	jl [0x25], [0x27], LABEL_0419
	sub [0x07], [0x24]
	jg [0x07], [0x27], LABEL_0419
	mov [0x07], [0x27]

LABEL_0419:
	jg [0x26], [0x28], LABEL_042B
	add [0x08], [0x24]
	jl [0x08], [0x28], LABEL_042B
	mov [0x08], [0x28]

LABEL_042B:
	jl [0x26], [0x28], LABEL_043D
	sub [0x08], [0x24]
	jg [0x08], [0x28], LABEL_043D
	mov [0x08], [0x28]

LABEL_043D:
	jne [0x07], [0x27], JUNK__0467
	jne [0x08], [0x28], JUNK__0467
	jmp LABEL_033B

COPY_VAR_27_28_TO_07_08:
	mov [0x07], [0x27]
	mov [0x08], [0x28]

LABEL_0452:
	video type=1, offset=CINEMATIC_002, x=[0x07], y=[0x08], zoom=0x40	;@raw=0x54,0x00,0xC4,0x07,0x08
	break
	jne [HERO_POS_UP_DOWN], 0x00, LABEL_0452
	jne [HERO_POS_MASK], 0x00, LABEL_0452
	jmp LABEL_033B

JUNK__0467:
	video type=1, offset=CINEMATIC_002, x=[0x07], y=[0x08], zoom=0x40	;@raw=0x54,0x00,0xC4,0x07,0x08
	break
	jmp JUNK__03F5
LABEL_0470:
	db 0x11

LABEL_0471:
	jne [0x1E], 0x15, LABEL_0493
	jne [0x1F], 0x0D, LABEL_0493
	jne [0x20], 0x14, LABEL_0493
	jne [0x21], 0x0D, LABEL_0493
	mov [0x00], 0x000A
	bankSwitch 2;  TODO - Name this stage (bank number #2)	;@raw=0x19,0x3E,0x82
	jmp LABEL_07BB

LABEL_0493:
	jne [0x1E], 0x11, LABEL_04B5
	jne [0x1F], 0x1D, LABEL_04B5
	jne [0x20], 0x0D, LABEL_04B5
	jne [0x21], 0x0C, LABEL_04B5
	mov [0x00], 0x0014
	bankSwitch 3;  TODO - Name this stage (bank number #3)	;@raw=0x19,0x3E,0x83
	jmp LABEL_07BB

LABEL_04B5:
	jne [0x1E], 0x0C, LABEL_04D7
	jne [0x1F], 0x15, LABEL_04D7
	jne [0x20], 0x15, LABEL_04D7
	jne [0x21], 0x0D, LABEL_04D7
	mov [0x00], 0x001E
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_04D7:
	jne [0x1E], 0x0F, LABEL_04F9
	jne [0x1F], 0x21, LABEL_04F9
	jne [0x20], 0x15, LABEL_04F9
	jne [0x21], 0x0C, LABEL_04F9
	mov [0x00], 0x0023
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_04F9:
	jne [0x1E], 0x14, LABEL_051B
	jne [0x1F], 0x1B, LABEL_051B
	jne [0x20], 0x0F, LABEL_051B
	jne [0x21], 0x14, LABEL_051B
	mov [0x00], 0x0025
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_051B:
	jne [0x1E], 0x21, LABEL_053D
	jne [0x1F], 0x0D, LABEL_053D
	jne [0x20], 0x0D, LABEL_053D
	jne [0x21], 0x13, LABEL_053D
	mov [0x00], 0x0021
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_053D:
	jne [0x1E], 0x15, LABEL_055F
	jne [0x1F], 0x0B, LABEL_055F
	jne [0x20], 0x14, LABEL_055F
	jne [0x21], 0x10, LABEL_055F
	mov [0x00], 0x001F
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_055F:
	jne [0x1E], 0x14, LABEL_0581
	jne [0x1F], 0x15, LABEL_0581
	jne [0x20], 0x0F, LABEL_0581
	jne [0x21], 0x0B, LABEL_0581
	mov [0x00], 0x0027
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_0581:
	jne [0x1E], 0x1D, LABEL_05A3
	jne [0x1F], 0x1D, LABEL_05A3
	jne [0x20], 0x0C, LABEL_05A3
	jne [0x21], 0x1D, LABEL_05A3
	mov [0x00], 0x0029
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_05A3:
	jne [0x1E], 0x0D, LABEL_05C5
	jne [0x1F], 0x0D, LABEL_05C5
	jne [0x20], 0x1B, LABEL_05C5
	jne [0x21], 0x21, LABEL_05C5
	mov [0x00], 0x002A
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_05C5:
	jne [0x1E], 0x1D, LABEL_05E7
	jne [0x1F], 0x0B, LABEL_05E7
	jne [0x20], 0x11, LABEL_05E7
	jne [0x21], 0x14, LABEL_05E7
	mov [0x00], 0x002B
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_05E7:
	jne [0x1E], 0x0B, LABEL_0609
	jne [0x1F], 0x1B, LABEL_0609
	jne [0x20], 0x1D, LABEL_0609
	jne [0x21], 0x0D, LABEL_0609
	mov [0x00], 0x0031
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_0609:
	jne [0x1E], 0x0C, LABEL_062B
	jne [0x1F], 0x14, LABEL_062B
	jne [0x20], 0x13, LABEL_062B
	jne [0x21], 0x15, LABEL_062B
	mov [0x00], 0x0032
	bankSwitch 5;  TODO - Name this stage (bank number #5)	;@raw=0x19,0x3E,0x85
	jmp LABEL_07BB

LABEL_062B:
	jne [0x1E], 0x15, LABEL_064D
	jne [0x1F], 0x0F, LABEL_064D
	jne [0x20], 0x0C, LABEL_064D
	jne [0x21], 0x14, LABEL_064D
	mov [0x00], 0x003C
	bankSwitch 6;  Secret Code Entry Screen	;@raw=0x19,0x3E,0x86
	jmp LABEL_07BB

LABEL_064D:
	jne [0x1E], 0x0B, LABEL_066F
	jne [0x1F], 0x0F, LABEL_066F
	jne [0x20], 0x15, LABEL_066F
	jne [0x21], 0x21, LABEL_066F
	mov [0x00], 0x002C
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_066F:
	jne [0x1E], 0x21, LABEL_0691
	jne [0x1F], 0x13, LABEL_0691
	jne [0x20], 0x1B, LABEL_0691
	jne [0x21], 0x1D, LABEL_0691
	mov [0x00], 0x002D
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_0691:
	jne [0x1E], 0x11, LABEL_06B3
	jne [0x1F], 0x1B, LABEL_06B3
	jne [0x20], 0x1D, LABEL_06B3
	jne [0x21], 0x0B, LABEL_06B3
	mov [0x00], 0x002E
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_06B3:
	jne [0x1E], 0x11, LABEL_06D5
	jne [0x1F], 0x0B, LABEL_06D5
	jne [0x20], 0x11, LABEL_06D5
	jne [0x21], 0x14, LABEL_06D5
	mov [0x00], 0x002F
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_06D5:
	jne [0x1E], 0x13, LABEL_06F7
	jne [0x1F], 0x0C, LABEL_06F7
	jne [0x20], 0x10, LABEL_06F7
	jne [0x21], 0x0B, LABEL_06F7
	mov [0x00], 0x0030
	bankSwitch 4;  TODO - Name this stage (bank number #4)	;@raw=0x19,0x3E,0x84
	jmp LABEL_07BB

LABEL_06F7:
	jne [0x1E], 0x11, LABEL_0719
	jne [0x1F], 0x11, LABEL_0719
	jne [0x20], 0x0F, LABEL_0719
	jne [0x21], 0x15, LABEL_0719
	mov [0x00], 0x003E
	bankSwitch 6;  Secret Code Entry Screen	;@raw=0x19,0x3E,0x86
	jmp LABEL_07BB

LABEL_0719:
	jne [0x1E], 0x1D, LABEL_073B
	jne [0x1F], 0x0F, LABEL_073B
	jne [0x20], 0x0B, LABEL_073B
	jne [0x21], 0x0B, LABEL_073B
	mov [0x00], 0x0040
	bankSwitch 6;  Secret Code Entry Screen	;@raw=0x19,0x3E,0x86
	jmp LABEL_07BB

LABEL_073B:
	jne [0x1E], 0x1D, LABEL_075D
	jne [0x1F], 0x21, LABEL_075D
	jne [0x20], 0x11, LABEL_075D
	jne [0x21], 0x0F, LABEL_075D
	mov [0x00], 0x0042
	bankSwitch 6;  Secret Code Entry Screen	;@raw=0x19,0x3E,0x86
	jmp LABEL_07BB

LABEL_075D:
	jne [0x1E], 0x14, LABEL_077F
	jne [0x1F], 0x1B, LABEL_077F
	jne [0x20], 0x1D, LABEL_077F
	jne [0x21], 0x0D, LABEL_077F
	mov [0x00], 0x0046
	load id=0x3E87
	jmp LABEL_07BB

LABEL_077F:
	jne [0x1E], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x1F], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x20], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	jne [0x21], 0xFFFF, SET_VAR_E6_F_PAUSE_4
	mov [0x00], 0x0000
	bankSwitch 1;  Prison	;@raw=0x19,0x3E,0x81
	jmp LABEL_07BB

SET_VAR_E6_F_PAUSE_4:
	mov [0xE6], 0x000F
	mov [PAUSE_SLICES], 0x0004

LABEL_07AD:
	text id=0x013F, x=7, y=100, color=0x05 ; "   PASSWORD INVALID!"
	break
	djnz [0xE6], LABEL_07AD
	jmp LABEL_0000

LABEL_07BB:
	setPalette 0x00	;@raw=0x0B,0x00,0xFF
	jmp LABEL_0000
LABEL_07C1:
	db 0x11

LABEL_07C2:
	jne [LAST_KEYCHAR], 0x0D, LABEL_07CD
	mov [0x06], 0x0063
	ret

LABEL_07CD:
	jne [LAST_KEYCHAR], 0x08, LABEL_07D8
	mov [0x06], 0x0062
	ret

LABEL_07D8:
	jl [LAST_KEYCHAR], 0x41, CLEAR_LAST_KEYCHAR
	jg [LAST_KEYCHAR], 0x5A, CLEAR_LAST_KEYCHAR
	mov [0x06], [LAST_KEYCHAR]
	sub [0x06], 0x0037
	ret

CLEAR_LAST_KEYCHAR:
	mov [LAST_KEYCHAR], 0x0000
	ret

LABEL_07F1:
	mov [0x05], [0x01]
	je [LAST_KEYCHAR], 0x00, LABEL_0806
	call LABEL_07C2
	je [LAST_KEYCHAR], 0x00, LABEL_0865
	jmp LABEL_0809

LABEL_0806:
	call LABEL_001F

LABEL_0809:
	mov [0x22], [0x02]
	je [0x06], 0x63, LABEL_0471
	jne [0x06], 0x62, LABEL_082D
	mov [0x06], 0xFFFF
	sub [0x22], 0x0001
	jg [0x22], 0x00, LABEL_083B
	mov [0x22], 0x0000
	jmp LABEL_083B

LABEL_082D:
	je [0x02], 0x04, LABEL_0865
	add [0x22], 0x0001
	add [0x02], 0x0001

LABEL_083B:
	jne [0x02], 0x01, LABEL_0844
	mov [0x1E], [0x06]

LABEL_0844:
	jne [0x02], 0x02, LABEL_084D
	mov [0x1F], [0x06]

LABEL_084D:
	jne [0x02], 0x03, LABEL_0856
	mov [0x20], [0x06]

LABEL_0856:
	jne [0x02], 0x04, LABEL_085F
	mov [0x21], [0x06]

LABEL_085F:
	call LABEL_0892
	mov [0x02], [0x22]

LABEL_0865:
	mov [0x05], [0x01]
	call LABEL_08CD
	video type=1, offset=CINEMATIC_002, x=[0x07], y=[0x08], zoom=0x40	;@raw=0x54,0x00,0xC4,0x07,0x08
	break
	jne [LAST_KEYCHAR], 0x00, LABEL_0865
	je [0xDB], 0x00, LABEL_0888
	jne [HERO_POS_JUMP_DOWN], 0xFFFF, LABEL_0888
	mov [HERO_ACTION], 0x0001

LABEL_0888:
	jne [HERO_ACTION], 0x00, LABEL_0865
	jmp LABEL_033B
LABEL_0891:
	db 0x11

LABEL_0892:
	mov [0x07], 0x00BC
	mov [0x08], 0x0054
	selectVideoPage 0x00
	video type=1, offset=CINEMATIC_003, x=160, y=100	;@raw=0x80,0xE6,0xA0,0x64
	text id=0x013C, x=2, y=80, color=0x06 ; "        ACCESS CODE:"
	mov [0x06], [0x1E]
	call LABEL_0B8D
	add [0x07], 0x0008
	mov [0x06], [0x1F]
	call LABEL_0B8D
	add [0x07], 0x0008
	mov [0x06], [0x20]
	call LABEL_0B8D
	add [0x07], 0x0008
	mov [0x06], [0x21]
	call LABEL_0B8D
	selectVideoPage 0xFF
	ret

LABEL_08CD:
	mov [0x07], [0x05]
	mov [0x08], [0x05]
	and [0x07], 0x0007
	and [0x08], 0x0008
	jne [0x08], 0x00, INIT_VAR08_TO_150
	mov [0x08], 0x0086
	jmp SCALE_VAR07_TIMES_9_PLUS_4A

INIT_VAR08_TO_150:
	mov [0x08], 0x0096

SCALE_VAR07_TIMES_9_PLUS_4A:
	shl [0x07], 0x0003
	mov [0xF8], [0x07]
	add [0x07], [0xF8]
	add [0x07], 0x004A
	je [0xDB], 0x00, SHARED_RET
	add [0x07], 0x0004
	ret

LABEL_0905:
	je [0x07], 0xC4, LABEL_09B9
	je [0x07], 0xCC, LABEL_0A55
	je [0x07], 0xD4, LABEL_0AF1
	jne [0x07], 0xBC, SHARED_RET
	jne [0x06], 0x0B, LABEL_092A
	text id=0x012E, x=23, y=80, color=0x04 ; "B"
	ret

LABEL_092A:
	jne [0x06], 0x0C, LABEL_0937
	text id=0x012F, x=23, y=80, color=0x04 ; "C"
	ret

LABEL_0937:
	jne [0x06], 0x0D, LABEL_0944
	text id=0x0130, x=23, y=80, color=0x04 ; "D"
	ret

LABEL_0944:
	jne [0x06], 0x0F, DRAW_LETTER_G_AT_X23
	text id=0x0131, x=23, y=80, color=0x04 ; "F"
	ret

DRAW_LETTER_G_AT_X23:
	jne [0x06], 0x10, DRAW_LETTER_H_AT_X23
	text id=0x0132, x=23, y=80, color=0x04 ; "G"
	ret

DRAW_LETTER_H_AT_X23:
	jne [0x06], 0x11, DRAW_LETTER_J_AT_X23
	text id=0x0133, x=23, y=80, color=0x04 ; "H"
	ret

DRAW_LETTER_J_AT_X23:
	jne [0x06], 0x13, DRAW_LETTER_K_AT_X23
	text id=0x0134, x=23, y=80, color=0x04 ; "J"
	ret

DRAW_LETTER_K_AT_X23:
	jne [0x06], 0x14, DRAW_LETTER_L_AT_X23
	text id=0x0135, x=23, y=80, color=0x04 ; "K"
	ret

DRAW_LETTER_L_AT_X23:
	jne [0x06], 0x15, DRAW_LETTER_R_AT_X23
	text id=0x0136, x=23, y=80, color=0x04 ; "L"
	ret

DRAW_LETTER_R_AT_X23:
	jne [0x06], 0x1B, DRAW_LETTER_X_AT_X23
	text id=0x0137, x=23, y=80, color=0x04 ; "R"
	ret

DRAW_LETTER_X_AT_X23:
	jne [0x06], 0x21, DRAW_LETTER_T_AT_X23
	text id=0x0138, x=23, y=80, color=0x04 ; "X"
	ret

DRAW_LETTER_T_AT_X23:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=23, y=80, color=0x04 ; "T"
	ret

LABEL_09B9:
	jne [0x06], 0x0B, LABEL_09C6
	text id=0x012E, x=24, y=80, color=0x04 ; "B"
	ret

LABEL_09C6:
	jne [0x06], 0x0C, LABEL_09D3
	text id=0x012F, x=24, y=80, color=0x04 ; "C"
	ret

LABEL_09D3:
	jne [0x06], 0x0D, LABEL_09E0
	text id=0x0130, x=24, y=80, color=0x04 ; "D"
	ret

LABEL_09E0:
	jne [0x06], 0x0F, DRAW_LETTER_G_AT_X24
	text id=0x0131, x=24, y=80, color=0x04 ; "F"
	ret

DRAW_LETTER_G_AT_X24:
	jne [0x06], 0x10, DRAW_LETTER_H_AT_X24
	text id=0x0132, x=24, y=80, color=0x04 ; "G"
	ret

DRAW_LETTER_H_AT_X24:
	jne [0x06], 0x11, DRAW_LETTER_J_AT_X24
	text id=0x0133, x=24, y=80, color=0x04 ; "H"
	ret

DRAW_LETTER_J_AT_X24:
	jne [0x06], 0x13, DRAW_LETTER_K_AT_X24
	text id=0x0134, x=24, y=80, color=0x04 ; "J"
	ret

DRAW_LETTER_K_AT_X24:
	jne [0x06], 0x14, DRAW_LETTER_L_AT_X24
	text id=0x0135, x=24, y=80, color=0x04 ; "K"
	ret

DRAW_LETTER_L_AT_X24:
	jne [0x06], 0x15, DRAW_LETTER_R_AT_X24
	text id=0x0136, x=24, y=80, color=0x04 ; "L"
	ret

DRAW_LETTER_R_AT_X24:
	jne [0x06], 0x1B, DRAW_LETTER_X_AT_X24
	text id=0x0137, x=24, y=80, color=0x04 ; "R"
	ret

DRAW_LETTER_X_AT_X24:
	jne [0x06], 0x21, DRAW_LETTER_T_AT_X24
	text id=0x0138, x=24, y=80, color=0x04 ; "X"
	ret

DRAW_LETTER_T_AT_X24:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=24, y=80, color=0x04 ; "T"
	ret

LABEL_0A55:
	jne [0x06], 0x0B, LABEL_0A62
	text id=0x012E, x=25, y=80, color=0x04 ; "B"
	ret

LABEL_0A62:
	jne [0x06], 0x0C, LABEL_0A6F
	text id=0x012F, x=25, y=80, color=0x04 ; "C"
	ret

LABEL_0A6F:
	jne [0x06], 0x0D, LABEL_0A7C
	text id=0x0130, x=25, y=80, color=0x04 ; "D"
	ret

LABEL_0A7C:
	jne [0x06], 0x0F, DRAW_LETTER_G_AT_X25
	text id=0x0131, x=25, y=80, color=0x04 ; "F"
	ret

DRAW_LETTER_G_AT_X25:
	jne [0x06], 0x10, DRAW_LETTER_H_AT_X25
	text id=0x0132, x=25, y=80, color=0x04 ; "G"
	ret

DRAW_LETTER_H_AT_X25:
	jne [0x06], 0x11, DRAW_LETTER_J_AT_X25
	text id=0x0133, x=25, y=80, color=0x04 ; "H"
	ret

DRAW_LETTER_J_AT_X25:
	jne [0x06], 0x13, DRAW_LETTER_K_AT_X25
	text id=0x0134, x=25, y=80, color=0x04 ; "J"
	ret

DRAW_LETTER_K_AT_X25:
	jne [0x06], 0x14, DRAW_LETTER_L_AT_X25
	text id=0x0135, x=25, y=80, color=0x04 ; "K"
	ret

DRAW_LETTER_L_AT_X25:
	jne [0x06], 0x15, DRAW_LETTER_R_AT_X25
	text id=0x0136, x=25, y=80, color=0x04 ; "L"
	ret

DRAW_LETTER_R_AT_X25:
	jne [0x06], 0x1B, DRAW_LETTER_X_AT_X25
	text id=0x0137, x=25, y=80, color=0x04 ; "R"
	ret

DRAW_LETTER_X_AT_X25:
	jne [0x06], 0x21, DRAW_LETTER_T_AT_X25
	text id=0x0138, x=25, y=80, color=0x04 ; "X"
	ret

DRAW_LETTER_T_AT_X25:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=25, y=80, color=0x04 ; "T"
	ret

LABEL_0AF1:
	jne [0x06], 0x0B, LABEL_0AFE
	text id=0x012E, x=26, y=80, color=0x04 ; "B"
	ret

LABEL_0AFE:
	jne [0x06], 0x0C, LABEL_0B0B
	text id=0x012F, x=26, y=80, color=0x04 ; "C"
	ret

LABEL_0B0B:
	jne [0x06], 0x0D, LABEL_0B18
	text id=0x0130, x=26, y=80, color=0x04 ; "D"
	ret

LABEL_0B18:
	jne [0x06], 0x0F, DRAW_LETTER_G_AT_X26
	text id=0x0131, x=26, y=80, color=0x04 ; "F"
	ret

DRAW_LETTER_G_AT_X26:
	jne [0x06], 0x10, DRAW_LETTER_H_AT_X26
	text id=0x0132, x=26, y=80, color=0x04 ; "G"
	ret

DRAW_LETTER_H_AT_X26:
	jne [0x06], 0x11, DRAW_LETTER_J_AT_X26
	text id=0x0133, x=26, y=80, color=0x04 ; "H"
	ret

DRAW_LETTER_J_AT_X26:
	jne [0x06], 0x13, DRAW_LETTER_K_AT_X26
	text id=0x0134, x=26, y=80, color=0x04 ; "J"
	ret

DRAW_LETTER_K_AT_X26:
	jne [0x06], 0x14, DRAW_LETTER_L_AT_X26
	text id=0x0135, x=26, y=80, color=0x04 ; "K"
	ret

DRAW_LETTER_L_AT_X26:
	jne [0x06], 0x15, DRAW_LETTER_R_AT_X26
	text id=0x0136, x=26, y=80, color=0x04 ; "L"
	ret

DRAW_LETTER_R_AT_X26:
	jne [0x06], 0x1B, DRAW_LETTER_X_AT_X26
	text id=0x0137, x=26, y=80, color=0x04 ; "R"
	ret

DRAW_LETTER_X_AT_X26:
	jne [0x06], 0x21, DRAW_LETTER_T_AT_X26
	text id=0x0138, x=26, y=80, color=0x04 ; "X"
	ret

DRAW_LETTER_T_AT_X26:
	jne [0x06], 0x1D, SHARED_RET
	text id=0x0139, x=26, y=80, color=0x04 ; "T"
	ret

LABEL_0B8D:
	je [0x06], 0x62, DRAW_LETTER_VIA_CIN_DISPATCH
	je [0x06], 0x63, DRAW_LETTER_VIA_CIN_DISPATCH
	jne [0xDB], 0x00, LABEL_0905

DRAW_LETTER_VIA_CIN_DISPATCH:
	jne [0x06], 0x62, DRAW_CIN_000_LETTER_BLANK
	video type=1, offset=CINEMATIC_001, x=[0x07], y=[0x08], zoom=[0x04]	;@raw=0x55,0x01,0x6C,0x07,0x08,0x04
	ret

DRAW_CIN_000_LETTER_BLANK:
	jne [0x06], 0x63, SHARED_RET
	video type=1, offset=CINEMATIC_000, x=[0x07], y=[0x08], zoom=[0x04]	;@raw=0x55,0x01,0x4C,0x07,0x08,0x04
	ret

SHARED_RET:
	ret
	killChannel
	video type=1, offset=CINEMATIC_004, x=160, y=100	;@raw=0x80,0x06,0xA0,0x64

LABEL_0BBF:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	copyVideoPage src=0x00, dst=0xFF
	break
	jmp LABEL_0BBF

JUNK__0BCA:
	blitFramebuffer 0xFF
	selectVideoPage 0xFF
	break
	jmp JUNK__0BCA

LABEL_0BD2:
	fill page=0x01, color=0x00
	fill page=0x02, color=0x00
	selectVideoPage 0x01
	blitFramebuffer 0x01
	blitFramebuffer 0xFF
	blitFramebuffer 0x02
	ret
LABEL_0BE1:
	db 0x11, 0x11, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
	FILL(62487, 0xFF)
