LABEL_4AC9:
	video offset=CINEMATIC_596, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_597, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_598, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_599, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_600, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_601, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_602, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_603, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_604, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_605, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_606, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_607, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_608, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_609, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_610, x=[BUDDY_X], y=[BUDDY_Y]
	setup channel=0x22, address=DRAW_CIN_229_TO_632_2F_AT_1C4A817A
	break
	video offset=CINEMATIC_611, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_612, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_613, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_614, x=[BUDDY_X], y=[BUDDY_Y]
	setup channel=0x22, address=KILL_CHANNEL_LANDING
	break
	video offset=CINEMATIC_342, x=[BUDDY_X], y=[BUDDY_Y]
	break
	setup channel=0x08, address=DRAW_CIN_628_TO_625_4F_AT_2F47D6D0
	video offset=CINEMATIC_615, x=[BUDDY_X], y=[BUDDY_Y]
	video offset=CINEMATIC_616, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_617, x=[BUDDY_X], y=[BUDDY_Y]
	video offset=CINEMATIC_618, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_619, x=[BUDDY_X], y=[BUDDY_Y]
	video offset=CINEMATIC_620, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_621, x=[BUDDY_X], y=[BUDDY_Y]
	video offset=CINEMATIC_622, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_623, x=[BUDDY_X], y=[BUDDY_Y]
	video offset=CINEMATIC_622, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_620, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_618, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_620, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_622, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_622, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_618, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_616, x=[BUDDY_X], y=[BUDDY_Y]
	break
	video offset=CINEMATIC_616, x=[BUDDY_X], y=[BUDDY_Y]
	setup channel=0x21, address=LABEL_1426
	setup channel=0x22, address=LABEL_1BC4
	setup channel=0x24, address=LABEL_1449
	mov [HACK_VAR_67], 0x0001
	mov [0x68], 0x0118
	mov [0x69], 0x00B6
	mov [0x6A], 0x0001
	mov [0x6B], 0x2000
	mov [0x6D], 0x0011
	break
	video offset=CINEMATIC_616, x=[BUDDY_X], y=[BUDDY_Y]
	setup channel=0x08, address=DRAW_CIN_624_TO_628_5F_AT_499AFE0A
	killChannel
