LABEL_4AC9:
	video type=1, offset=CINEMATIC_596, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_597, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_598, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_599, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_600, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_601, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_602, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_603, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_604, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_605, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_606, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_607, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_608, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_609, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_610, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x22, address=DRAW_CIN_229_TO_632_2F_AT_1C4A817A
	break
	video type=1, offset=CINEMATIC_611, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_612, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_613, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_614, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x22, address=0x017F
	break
	video type=1, offset=CINEMATIC_342, x=[0x07], y=[0x08], zoom=0x40
	break
	setup channel=0x08, address=DRAW_CIN_628_TO_625_4F_AT_2F47D6D0
	video type=1, offset=CINEMATIC_615, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_616, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_617, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_618, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_619, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_620, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_621, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_622, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_623, x=[0x07], y=[0x08], zoom=0x40
	video type=1, offset=CINEMATIC_622, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_620, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_618, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_620, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_622, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_622, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_618, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_616, x=[0x07], y=[0x08], zoom=0x40
	break
	video type=1, offset=CINEMATIC_616, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x21, address=LABEL_1426
	setup channel=0x22, address=LABEL_1BC4
	setup channel=0x24, address=LABEL_1449
	mov [HACK_VAR_67], 0x0001
	mov [0x68], 0x0118
	mov [0x69], 0x00B6
	mov [0x6A], 0x0001
	mov [0x6B], 0x2000
	mov [0x6D], 0x0011
	break
	video type=1, offset=CINEMATIC_616, x=[0x07], y=[0x08], zoom=0x40
	setup channel=0x08, address=DRAW_CIN_624_TO_628_5F_AT_499AFE0A
	killChannel
